"use client";
import {use,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase";
import {trackCustomerActivity} from "@/lib/customer-activity";
const pretty=(s:string)=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());const ESCALATION_LEVELS=['Support','Senior Support','Admin','Superadmin'];
export default function Ticket({params}:{params:Promise<{id:string}>}){const {id}=use(params),sb=createClient(),bodyRef=useRef<HTMLTextAreaElement>(null);const [ticket,setTicket]=useState<any>(),[messages,setMessages]=useState<any[]>([]),[attachments,setAttachments]=useState<any[]>([]),[body,setBody]=useState(''),[files,setFiles]=useState<File[]>([]),[msg,setMsg]=useState(''),[missing,setMissing]=useState(false);
async function load(){const {data:{user}}=await sb.auth.getUser();if(!user){setMissing(true);return}const t=await sb.from('support_tickets').select('*,support_departments(name,client_can_close)').eq('id',id).eq('user_id',user.id).maybeSingle();if(!t.data){setTicket(null);setMissing(true);return}const [m,a]=await Promise.all([sb.from('support_ticket_messages').select('*').eq('ticket_id',id).eq('internal_note',false).order('created_at'),sb.from('support_attachments').select('*').eq('ticket_id',id).order('created_at')]);setMissing(false);setTicket(t.data);setMessages(m.data||[]);setAttachments(a.data||[])}useEffect(()=>{load()},[id]);
async function notifySupport(eventKey:string){const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)return;await fetch('/api/mail/support-event',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({ticketId:id,eventKey})}).catch(()=>null)}
function format(mark:string){const el=bodyRef.current;if(!el)return;const a=el.selectionStart,b=el.selectionEnd,v=el.value,sel=v.slice(a,b)||'text';setBody(v.slice(0,a)+mark+sel+mark+v.slice(b));setTimeout(()=>el.focus(),0)}
async function upload(messageId:string){const {data:{user}}=await sb.auth.getUser();if(!user)return;for(const f of files){const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${user.id}/${id}/${crypto.randomUUID()}-${safe}`;const {error}=await sb.storage.from('support-attachments').upload(path,f);if(error)throw error;const {error:r}=await sb.rpc('attach_support_file',{p_ticket_id:id,p_message_id:messageId,p_file_name:f.name,p_storage_path:path,p_mime_type:f.type||null,p_file_size_bytes:f.size});if(r)throw r}}
async function reply(){if(!body.trim())return;setMsg(ticket?.status==='closed'?'Reopening ticket and sending reply…':'Sending reply…');const {data,error}=await sb.rpc('customer_reply_support_ticket',{p_ticket_id:id,p_body:body});if(error)return setMsg(error.message);try{await upload(data.message_id)}catch(x:any){setMsg(`Reply sent, attachment failed: ${x.message}`);return}setBody('');setFiles([]);if(data.reopened){await notifySupport('support.ticket.reopened');await trackCustomerActivity('support.ticket_reopened',{entityType:'support_ticket',entityId:id})}else await trackCustomerActivity('support.ticket_replied',{entityType:'support_ticket',entityId:id});setMsg(data.reopened?'Ticket reopened and reply sent.':'Reply sent.');load()}
async function closeTicket(){if(!confirm('Close this support ticket? You can reply later to reopen it.'))return;const {error}=await sb.rpc('customer_close_support_ticket',{p_ticket_id:id});setMsg(error?.message||'Ticket closed.');if(!error){await notifySupport('support.ticket.closed');await trackCustomerActivity('support.ticket_closed',{entityType:'support_ticket',entityId:id});load()}}
async function openFile(a:any){const {data,error}=await sb.storage.from('support-attachments').createSignedUrl(a.storage_path,600);if(error)return setMsg(error.message);await trackCustomerActivity('support.attachment_opened',{entityType:'support_ticket',entityId:id,detail:{file_name:a.file_name}});window.open(data.signedUrl,'_blank')}
if(missing)return <main className="portalPage"><h1>Ticket not found</h1><p className="muted">This ticket does not belong to the signed-in customer account.</p></main>;if(!ticket)return <main className="portalPage">Loading ticket…</main>;const closed=ticket.status==='closed',canCustomerClose=!!ticket.support_departments?.client_can_close,escalationLevel=Number(ticket.escalation_level||0),escalationLabel=ESCALATION_LEVELS[Math.max(0,Math.min(3,escalationLevel))];return <main className="portalPage supportTicketV3"><header className="portalTop"><div><p className="eyebrow">TICKET #{ticket.ticket_number}</p><h1>{ticket.subject}</h1><p className="muted">{ticket.support_departments?.name||'Support'} · {pretty(ticket.status)} · {pretty(ticket.priority)}</p></div><div className="inlineActions"><Link href="/portal/support">← Tickets</Link>{!closed&&canCustomerClose&&<button className="danger" onClick={closeTicket}>Close ticket</button>}</div></header>
<section className="stats four"><article><small>Status</small><strong>{pretty(ticket.status)}</strong></article><article><small>Priority</small><strong>{pretty(ticket.priority)}</strong></article><article><small>Department</small><strong>{ticket.support_departments?.name||'—'}</strong></article><article><small>Updated</small><strong>{new Date(ticket.updated_at).toLocaleDateString()}</strong></article></section>
{escalationLevel>0&&<div className="notice supportPortalEscalation"><b>Escalated to {escalationLabel}</b><span>{ticket.assigned_to?`Your ticket has been claimed and is being handled at the ${escalationLabel} tier.`:`Your ticket has been escalated for higher-level review and is waiting for the ${escalationLabel} tier to claim it.`}</span></div>}
{!closed&&!canCustomerClose&&<div className="notice"><b>Staff-managed closure</b><span>This department keeps ticket closure with the support team. You can continue replying here until Support closes the case.</span></div>}
{ticket.related_order_id&&<section className="panel"><div className="panelTitle"><div><h2>Associated order</h2><p className="muted">This ticket is linked to one of your purchases.</p></div><Link href={`/portal/orders/${ticket.related_order_id}`}>View order →</Link></div></section>}
<section className="panel"><div className="panelTitle"><div><h2>Conversation</h2><p className="muted">Messages from you, Support and automatic ticket events.</p></div></div><div className="thread">{messages.map(m=><article className={`message ${m.author_role!=='user'?'staffMessage':''} ${m.author_role==='system'?'systemMessage':''}`} key={m.id}><div><b>{m.author_role==='user'?'You':m.author_role==='system'?'OrbitFS System':'Support'}</b><span>{new Date(m.created_at).toLocaleString()}</span></div><p>{m.body}</p></article>)}</div>{attachments.length>0&&<div className="attachmentList"><h3>Attachments</h3>{attachments.map(a=><button className="attachmentItem secondary" key={a.id} onClick={()=>openFile(a)}><span>{a.file_name}</span><small>{a.file_size_bytes?`${(Number(a.file_size_bytes)/1024/1024).toFixed(1)} MB`:''}</small></button>)}</div>}</section>
<section className="panel supportReplyBox"><div className="panelTitle"><div><h2>{closed?'Reopen ticket':'Reply'}</h2><p className="muted">{closed?'Replying to this closed ticket will automatically reopen it and notify Support.':'Your reply will mark the ticket as waiting for staff.'}</p></div></div><div className="editorToolbar"><button type="button" onClick={()=>format('**')}>Bold</button><button type="button" onClick={()=>format('_')}>Italic</button><button type="button" onClick={()=>format('`')}>Code</button></div><textarea ref={bodyRef} rows={8} value={body} onChange={e=>setBody(e.target.value)} placeholder={closed?'Write a reply to reopen this ticket…':'Write your reply…'}/><label>Attachments<input type="file" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label>{files.length>0&&<div className="attachmentDrafts">{files.map(f=><span key={f.name}>{f.name}</span>)}</div>}<button onClick={reply}>{closed?'Reopen & send reply':'Send reply'}</button><p>{msg}</p></section></main>}
