import {masterControlRelease,masterCreateRelease,masterPublishRelease,masterReleases,masterValidate} from "@/lib/master-api";
import {getMasterApiUrl} from "@/lib/license-master-config";
export type EngineReleaseStatus="draft"|"published"|"superseded"|"paused"|"withdrawn";
export type StoredEngineRelease={releaseChannel:string;version:string;releaseId:string;sourceCommit:string|null;sha256:string;size:number;fileCount:number;objectPath:string;projectSettings:any;components:string[];checkpointRequired:boolean;minimumEngineDeployerProtocol:number;status:EngineReleaseStatus;createdAt:string;candidateAt:string;publishedAt:string|null;updatedAt:string};
const normalize=(r:any):StoredEngineRelease=>({releaseChannel:String(r?.channel||"stable"),version:String(r?.version||""),releaseId:String(r?.id||r?.releaseId||""),sourceCommit:r?.manifest?.sourceCommit||null,sha256:String(r?.artifact?.sha256||r?.sha256||""),size:Number(r?.artifact?.size||r?.size||0),fileCount:Number(r?.manifest?.fileCount||r?.fileCount||0),objectPath:String(r?.artifact?.path||""),projectSettings:r?.manifest?.projectSettings||{},components:Array.isArray(r?.manifest?.components)?r.manifest.components:[],checkpointRequired:r?.manifest?.checkpointRequired!==false,minimumEngineDeployerProtocol:Math.max(1,Number(r?.manifest?.minimumEngineDeployerProtocol||1)),status:r?.status||"draft",createdAt:r?.createdAt||"",candidateAt:r?.createdAt||"",publishedAt:r?.publishedAt||null,updatedAt:r?.updatedAt||r?.createdAt||""});
export async function listEngineReleases(){const result=await masterReleases("orbitfs_base","all","update");const rows:any[]=result.releases||[];return rows.filter((r:any)=>String(r.release_type)==="update").map(normalize)}
export async function engineReleaseMetadata(version:string){return (await listEngineReleases()).find((r:StoredEngineRelease)=>r.version===version)||null}
export async function latestEngineMetadata(){const rows:StoredEngineRelease[]=(await listEngineReleases()).filter((r:StoredEngineRelease)=>r.status==="published");if(!rows[0])throw new Error("No published Engine release is currently available");return rows.sort((a:StoredEngineRelease,b:StoredEngineRelease)=>b.updatedAt.localeCompare(a.updatedAt))[0]}
export async function authorizeReleasePublisher(req:Request){return req.headers.get("authorization")?{ok:true as const}:{ok:false as const,status:401,error:"Release publisher authorization is required",code:"RELEASE_PUBLISH_UNAUTHORIZED"}}
export async function submitEngineReleaseDraft(input:any){const version=String(input.version||"").trim();if(!version)throw new Error("Engine release version is required");const created=await masterCreateRelease({component:String(input.component||"orbitfs_mcp"),product:"orbitfs_base",version,channel:String(input.channel||"stable").trim().toLowerCase()||"stable",release_type:"update",changelog:String(input.changelog||""),manifest:{sourceCommit:input.sourceCommit||null,components:input.components||["orbitfs_mcp","orbitfs_apex","orbitfs_studio"],checkpointRequired:true,minimumEngineDeployerProtocol:Number(input.minimumEngineDeployerProtocol||1)}});return normalize(created.release)}
export async function publishEngineReleaseDraft(version:string){const r=await engineReleaseMetadata(version);if(!r)throw new Error(`Engine release ${version} was not found`);return normalize((await masterPublishRelease(r.releaseId)).release)}
export async function setEngineReleaseStatus(version:string,status:"paused"|"withdrawn"){const r=await engineReleaseMetadata(version);if(!r)throw new Error(`Engine release ${version} was not found`);return normalize((await masterControlRelease(r.releaseId,status)).release)}
export async function latestEngineRelease(){const r=await latestEngineMetadata();const base=await getMasterApiUrl();return {...r,downloadUrl:`${base}/updater?release_id=${encodeURIComponent(r.releaseId)}&download=1`,expiresIn:300}}
export async function authorizeEngineRelease(input:any){const licenseKey=String(input?.licenseKey||input?.license_key||"").trim(),installationId=String(input?.installationId||input?.installation_id||"").trim();if(!licenseKey||!installationId)return {ok:false as const,status:400,error:"Licence key and installation id are required",code:"ENGINE_RELEASE_IDENTITY_REQUIRED"};const data=await masterValidate({licenseKey,installationId,activate:false,components:["orbitfs_mcp","orbitfs_apex","orbitfs_studio"]});if(data?.valid!==true)return {ok:false as const,status:403,error:"Licence is not valid for this installation",code:"ENGINE_RELEASE_LICENSE_INVALID"};return {ok:true as const,installationId,entitled:Object.keys(data.components||{}).filter((k:string)=>data.components[k]?.allowed)}}
