import {masterControlRelease,masterPublishRelease,masterReleases,masterValidateRelease} from "@/lib/master-api";
export type OrbitfsReleaseBundleChannel="base"|"update"; export type OrbitfsReleaseBundleStatus="draft"|"published"|"paused"|"superseded"|"withdrawn"|"failed"; export type OrbitfsArtifactSnapshot=Record<string,unknown>;
export type OrbitfsReleaseBundle={version:string;status:OrbitfsReleaseBundleStatus;channel:OrbitfsReleaseBundleChannel;releaseChannel:string;components:string[];minimumEngineDeployerProtocol:number;engineDeployerProtocol:number;technicalAnalysis:Record<string,unknown>;panel:any;engine:any;updatedAt:string;baseSourceCommit:string|null;engineSourceCommit:string|null};
function row(r:any):OrbitfsReleaseBundle{return {version:String(r?.version||""),status:r?.status||"draft",channel:r?.release_type==="update"||r?.channel==="update"?"update":"base",releaseChannel:String(r?.channel||"stable"),components:Array.isArray(r?.manifest?.components)?r.manifest.components:[],minimumEngineDeployerProtocol:Number(r?.manifest?.minimumEngineDeployerProtocol||1),engineDeployerProtocol:1,technicalAnalysis:{},panel:r?.id?{...r,id:r.id}:null,engine:null,updatedAt:r?.updatedAt||r?.createdAt||"",baseSourceCommit:r?.component==="orbitfs_base"?r?.manifest?.sourceCommit||null:null,engineSourceCommit:r?.channel==="update"?r?.manifest?.sourceCommit||null:null};}
export async function listOrbitfsReleaseBundles(limit=100){const [base,updates]=await Promise.all([masterReleases("orbitfs_base","all","base"),masterReleases("orbitfs_base","all","update")]);const releases=[...(base.releases||[]),...(updates.releases||[])];return releases.slice(0,limit).map((x:any)=>row(x));}
export async function getOrbitfsReleaseBundle(version:string){return (await listOrbitfsReleaseBundles(250)).find((x:OrbitfsReleaseBundle)=>x.version===version)||null;}
export async function syncOrbitfsReleaseBundle(input:any){const r=input.panel||input.engine;if(!r)return getOrbitfsReleaseBundle(String(input.version||""));return row(r);}
export function validateOrbitfsReleaseBundle(bundle:OrbitfsReleaseBundle){if(!bundle.version)throw new Error("Release bundle version is required");return bundle;}
export async function validateOrbitfsReleaseBundleInMaster(version:string){const r=await getOrbitfsReleaseBundle(version);if(!r)throw new Error(`Release bundle ${version} was not found`);const id=r.panel?.id||r.panel?.releaseId;if(!id)throw new Error(`Release bundle ${version} has no License Master release id`);return row((await masterValidateRelease(id)).release);}
export async function publishOrbitfsReleaseBundle(version:string){const r=await getOrbitfsReleaseBundle(version);if(!r)return null;const id=r.panel?.id||r.panel?.releaseId;if(!id)return r;await masterValidateRelease(id);return row((await masterPublishRelease(id)).release);}
export async function publishOrbitfsReleaseBundleArtifacts(version:string){return {bundle:await publishOrbitfsReleaseBundle(version),panel:(await getOrbitfsReleaseBundle(version))?.panel||null,engine:null};}
export async function setOrbitfsReleaseBundleStatus(version:string,status:"paused"|"withdrawn"|"failed"){const r=await getOrbitfsReleaseBundle(version);if(!r)return null;const id=r.panel?.id||r.panel?.releaseId;if(!id)return {...r,status};const mapped=status==="failed"?"paused":status;return row((await masterControlRelease(id,mapped)).release);}
