import {gunzipSync} from "node:zlib";
import {masterControlRelease,masterCreateRelease,masterDownloadReleaseArtifact,masterPublishRelease,masterReleases,masterValidate,masterUpdateRelease} from "@/lib/master-api";
export type PanelReleaseChannel="base"|"update"; export type PanelReleaseStatus="draft"|"published"|"paused"|"superseded"|"withdrawn"|"failed"; export type PanelReleaseRollout="internal"|"beta"|"public"; export type PanelReleaseSeverity="normal"|"important"|"critical"; export type ReleaseAudience="latest"|"beta"|"internal";
export type StoredPanelRelease={releaseChannel:string;version:string;releaseId:string;sourceCommit:string|null;schemaVersion:string;sha256:string;size:number;fileCount:number;objectPath:string;projectSettings:any;channel:PanelReleaseChannel;status:PanelReleaseStatus;title:string;description:string;changelog:string;customerNotes:string;internalNotes:string;severity:PanelReleaseSeverity;required:boolean;minimumVersion:string|null;rollbackVersion:string|null;rollout:PanelReleaseRollout;components:string[];createdAt:string;candidateAt:string;publishedAt:string|null;updatedAt:string};
export type PanelReleaseDraftPatch=Partial<Pick<StoredPanelRelease,"channel"|"title"|"description"|"changelog"|"customerNotes"|"internalNotes"|"severity"|"required"|"minimumVersion"|"rollbackVersion"|"rollout"|"components">>;
export function normalizePanelReleaseChannel(value:any):PanelReleaseChannel{const v=String(value||"").trim().toLowerCase();if(v==="base")return "base";if(v==="update"||v==="updates")return "update";throw new Error("Panel release channel must be base or update")}
export function normalizeReleaseAudience(value:any):ReleaseAudience{const v=String(value||"latest").trim().toLowerCase();if(v==="latest"||v==="stable"||v==="public")return "latest";if(v==="beta")return "beta";if(v==="internal"||v==="dev"||v==="development")return "internal";throw new Error("Release audience must be latest, beta, or internal")}
const normalize=(r:any):StoredPanelRelease=>({version:String(r?.version||""),releaseId:String(r?.id||r?.releaseId||""),sourceCommit:r?.source_sha||r?.sourceCommit||r?.manifest?.sourceCommit||null,schemaVersion:String(r?.manifest?.databaseSchemaVersion||r?.manifest?.releaseInfo?.databaseSchemaVersion||"1"),sha256:String(r?.checksum||r?.artifact?.sha256||r?.artifact_sha256||""),size:Number(r?.artifact?.size||r?.artifact_size||0),fileCount:Number(r?.manifest?.fileCount||0),objectPath:String(r?.artifact?.path||r?.artifact_path||""),projectSettings:r?.manifest?.projectSettings||{},releaseChannel:String(r?.channel||"stable"),channel:normalizePanelReleaseChannel(r?.release_type||r?.releaseType||"base"),status:r?.status||"draft",title:String(r?.manifest?.title||r?.title||""),description:String(r?.manifest?.description||r?.description||""),changelog:String(r?.notes||r?.changelog||""),customerNotes:String(r?.manifest?.customer_notes||r?.manifest?.customerNotes||r?.customer_notes||""),internalNotes:String(r?.manifest?.internal_notes||r?.manifest?.internalNotes||r?.internal_notes||""),severity:r?.manifest?.severity||r?.severity||"normal",required:r?.manifest?.required===true||r?.required===true,minimumVersion:r?.manifest?.minimum_version||r?.manifest?.minimumVersion||r?.minimum_version||null,rollbackVersion:r?.manifest?.rollback_version||r?.manifest?.rollbackVersion||r?.rollback_version||null,rollout:r?.manifest?.rollout||r?.rollout||"public",components:Array.isArray(r?.manifest?.components)?r.manifest.components:(Array.isArray(r?.components)?r.components:[]),createdAt:r?.createdAt||r?.created_at||"",candidateAt:r?.createdAt||r?.created_at||"",publishedAt:r?.publishedAt||r?.published_at||null,updatedAt:r?.updatedAt||r?.updated_at||r?.createdAt||r?.created_at||""});
export async function listPanelReleases(){const result=await masterReleases("orbitfs_base","all","base");const releases:any[]=result.releases||[];const base=releases.filter((r:any)=>String(r.release_type||r.releaseType)==="base").map(normalize);const updates=(await masterReleases("orbitfs_base","all","update")).releases||[];return [...base,...updates.map(normalize)]}
function audienceAllows(release:StoredPanelRelease,audience:ReleaseAudience){if(release.status!=="published")return false;if(audience==="internal")return true;if(audience==="beta")return release.rollout==="public"||release.rollout==="beta";return release.rollout==="public"}
export async function latestPanelMetadata(channel:PanelReleaseChannel="base",audience:ReleaseAudience="latest"){const rows:StoredPanelRelease[]=(await listPanelReleases()).filter((r:StoredPanelRelease)=>r.channel===channel&&audienceAllows(r,audience));return rows.sort((a:StoredPanelRelease,b:StoredPanelRelease)=>{const published=String(b.publishedAt||b.updatedAt).localeCompare(String(a.publishedAt||a.updatedAt));return published||b.version.localeCompare(a.version,undefined,{numeric:true})})[0]||null}
export async function getPanelRelease(version="latest",channel:PanelReleaseChannel="base"){const requested=String(version||"latest"),byId=requested.startsWith("release:"),prefixed=requested.startsWith("update:"),effectiveChannel=prefixed?"update":channel,effectiveVersion=prefixed?requested.slice(7):requested,effectiveReleaseId=byId?requested.slice(8):"";const rows=await listPanelReleases();const r=byId?rows.find((x:StoredPanelRelease)=>String(x.releaseId)===effectiveReleaseId):(effectiveVersion==="latest"?await latestPanelMetadata(effectiveChannel):rows.find((x:StoredPanelRelease)=>x.version===effectiveVersion&&x.channel===effectiveChannel));if(!r)throw new Error(`Panel release ${byId?effectiveReleaseId:effectiveVersion} was not found`);const downloaded=await masterDownloadReleaseArtifact(r.releaseId);const bytes=downloaded.bytes;let manifest:any={files:[],projectSettings:{}};try{manifest=JSON.parse(gunzipSync(bytes).toString("utf8"))}catch{throw new Error("Master release artifact is not a valid OrbitFS package")};return {metadata:r,manifest,bytes}}
export async function authorizePanelReleasePublisher(req:Request){const expected=String(process.env.PANEL_RELEASE_PUBLISHER_TOKEN||"").trim();const supplied=String(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!expected||!supplied||supplied!==expected)return {ok:false as const,status:401,error:"Release publisher authorization is required",code:"RELEASE_PUBLISH_UNAUTHORIZED"};return {ok:true as const}}
export async function submitPanelReleaseDraft(input:any){const version=String(input.version||"").trim();if(!version)throw new Error("Panel release version is required");const channel=normalizePanelReleaseChannel(input.channel||"base");const created=await masterCreateRelease({component:"orbitfs_base",product:"orbitfs_base",version,channel,release_type:channel==="update"?"update":"base",changelog:String(input.changelog||""),manifest:{sourceCommit:input.sourceCommit||null,title:input.title||`OrbitFS ${version}`,description:input.description||"",customerNotes:input.customerNotes||"",severity:input.severity||"normal",required:input.required===true,minimumVersion:input.minimumVersion||null,rollbackVersion:input.rollbackVersion||null,rollout:input.rollout||"public",components:input.components?String(input.components).split(",").map((x:string)=>x.trim()).filter(Boolean):["core"],databaseSchemaVersion:String(input.databaseSchemaVersion||input.schemaVersion||"1"),projectSettings:input.projectSettings||{}}});return normalize(created.release)}
export async function savePanelReleaseDraft(version:string,patch:PanelReleaseDraftPatch){const r=(await listPanelReleases()).find((x:StoredPanelRelease)=>x.version===version);if(!r)throw new Error(`Panel release ${version} was not found`);const updated=await masterUpdateRelease(r.releaseId,{title:patch.title,description:patch.description,changelog:patch.changelog,customer_notes:patch.customerNotes,internal_notes:patch.internalNotes,severity:patch.severity,required:patch.required,rollout:patch.rollout,minimum_version:patch.minimumVersion,rollback_version:patch.rollbackVersion,components:patch.components});return normalize(updated.release)}
export async function publishPanelReleaseDraft(version:string){const r=(await listPanelReleases()).find((x:StoredPanelRelease)=>x.version===version);if(!r)throw new Error(`Panel release ${version} was not found`);return normalize((await masterPublishRelease(r.releaseId)).release)}
export const publishPanelRelease=submitPanelReleaseDraft;
export async function setPanelReleaseStatus(version:string,status:"paused"|"withdrawn"){const r=(await listPanelReleases()).find((x:StoredPanelRelease)=>x.version===version);if(!r)throw new Error(`Panel release ${version} was not found`);return normalize((await masterControlRelease(r.releaseId,status)).release)}
export async function authorizePanelRelease(input:any){const licenseKey=String(input?.licenseKey||input?.license_key||"").trim(),installationId=String(input?.installationId||input?.installation_id||"").trim();if(!licenseKey||!installationId)return {ok:false as const,status:400,error:"Licence key and installation id are required",code:"PANEL_RELEASE_IDENTITY_REQUIRED"};const data=await masterValidate({licenseKey,installationId,activate:false,components:["orbitfs_base"]});if(data?.valid!==true)return {ok:false as const,status:403,error:"Licence is not valid for this installation",code:"PANEL_RELEASE_LICENSE_INVALID"};return {ok:true as const,installationId,entitledComponent:"orbitfs_base"}}
export async function latestPanelRelease(channel:PanelReleaseChannel="base",audience:ReleaseAudience="latest"){const r=await latestPanelMetadata(channel,audience);if(!r)throw new Error(`No published ${channel} Panel release is currently available for the selected rollout audience`);return r}
