"use client";

import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {createClient} from "@/lib/supabase";

const external=['stripe','paypal'];const labels:any={stripe:'Card payment Â· Stripe Checkout',paypal:'PayPal Checkout',account_credit:'OrbitFS account credit',manual_bank:'Manual bank transfer'};

export default function GatewaySetup(){const sb=createClient();const [rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState('stripe'),[status,setStatus]=useState<any>(),[form,setForm]=useState<any>({environment:'sandbox',currencies:['AUD'],credentials:{},webhook:{},metadata:{}}),[msg,setMsg]=useState('');

async function load(){const {data}=await sb.rpc('admin_gateway_setup_summary');const list=data||[];setRows(list);const cur=list.find((x:any)=>x.code===selected)||list[0];if(cur)setForm((f:any)=>({...f,environment:cur.environment||'sandbox',currencies:cur.currencies||['AUD'],webhook:cur.webhook_config||{},metadata:cur.metadata||{},credentials:{}}))}

async function autoWebhook(){setMsg('Registering webhook with provider…');const {data:{session}}=await sb.auth.getSession();if(!session)return setMsg('Session expired.');const r=await fetch('/api/payments/setup/webhook',{method:'POST',headers:{authorization:`Bearer ${session.access_token}`,'content-type':'application/json'},body:JSON.stringify({gateway:current.code})});const d=await r.json();setMsg(r.ok?'Webhook registered successfully.':d.error||'Webhook registration failed.');if(r.ok){await load();await verify()}}

async function verify(){setMsg('Verifying provider…');const {data:{session}}=await sb.auth.getSession();if(!session)return setMsg('Session expired.');const r=await fetch('/api/payments/status',{headers:{authorization:`Bearer ${session.access_token}`},cache:'no-store'});const d=await r.json();if(!r.ok){setStatus(undefined);return setMsg(d.error||'Verification failed.')}setStatus(d);setMsg('Verification complete.');await load()}

useEffect(()=>{load();verify()},[]);const current=useMemo(()=>rows.find(x=>x.code===selected)||rows[0],[rows,selected]);useEffect(()=>{if(current)setForm((f:any)=>({...f,environment:current.environment||'sandbox',currencies:current.currencies||['AUD'],webhook:current.webhook_config||{},metadata:current.metadata||{},credentials:{}}))},[current?.gateway_id]);

const has=(k:string)=>current?.configured_keys?.includes(k);async function saveSecret(k:string){const v=form.credentials?.[k];if(!v)return setMsg('Enter a value first.');setMsg(`Saving ${k.replaceAll('_',' ')}â€¦`);const {error}=await sb.rpc('admin_store_gateway_secret',{p_gateway_code:current.code,p_key:k,p_value:v});setMsg(error?.message||'Secret saved securely in Vault.');if(!error){setForm({...form,credentials:{...form.credentials,[k]:''}});await load()}}

async function removeSecret(k:string){if(!confirm(`Remove stored ${k.replaceAll('_',' ')}?`))return;const {error}=await sb.rpc('admin_remove_gateway_secret',{p_gateway_code:current.code,p_key:k});setMsg(error?.message||'Stored credential removed.');if(!error)load()}

async function saveSetup(){const {error}=await sb.rpc('admin_update_gateway_setup',{p_gateway_code:current.code,p_environment:form.environment,p_currencies:form.currencies,p_webhook_config:form.webhook||{},p_metadata:form.metadata||{}});setMsg(error?.message||'Gateway setup options saved.');if(!error)load()}

async function finishSetup(){
 setMsg('Finishing gateway setup?');
 const required=current?.provider==='stripe'?['secret_key']:current?.provider==='paypal'?['client_id','client_secret']:[];
 for(const key of required){const value=form.credentials?.[key];if(value){const {error}=await sb.rpc('admin_store_gateway_secret',{p_gateway_code:current.code,p_key:key,p_value:value});if(error)return setMsg(error.message)}else if(!has(key))return setMsg(`Missing ${key.replaceAll('_',' ')}.`)}
 const {error:setupError}=await sb.rpc('admin_update_gateway_setup',{p_gateway_code:current.code,p_environment:form.environment,p_currencies:form.currencies,p_webhook_config:form.webhook||{},p_metadata:form.metadata||{}});if(setupError)return setMsg(setupError.message);
 const {data:{session}}=await sb.auth.getSession();if(!session)return setMsg('Session expired.');
 const wr=await fetch('/api/payments/setup/webhook',{method:'POST',headers:{authorization:`Bearer ${session.access_token}`,'content-type':'application/json'},body:JSON.stringify({gateway:current.code})});const wd=await wr.json();if(!wr.ok)return setMsg(wd.error||'Automatic webhook registration failed.');
 const vr=await fetch('/api/payments/status',{headers:{authorization:`Bearer ${session.access_token}`},cache:'no-store'});const vd=await vr.json();if(!vr.ok)return setMsg(vd.error||'Provider verification failed.');setStatus(vd);await load();setForm((f:any)=>({...f,credentials:{}}));setMsg(`${current.display_name||current.code} setup complete.`)
}


const keys=current?.provider==='stripe'?[['secret_key','Stripe secret key','sk_live_? / sk_test_?']]:current?.provider==='paypal'?[['client_id','PayPal client ID','Client ID'],['client_secret','PayPal client secret','Client secret']]:[];

const ready=current?.setup_status==='ready';return <main className="adminShell"><header className="adminTop"><div><p className="eyebrow">ORDERS & BILLING</p><h1>Gateway setup</h1><p className="muted">Install, secure, verify and activate payment providers. Credentials are stored in Supabase Vault and never returned to the browser.</p></div><div className="inlineActions"><Link className="buttonlink secondary" href="/admin/payments">Configure gateways</Link><button onClick={verify}>Verify all</button></div></header>

<section className="gatewaySetupWorkspace"><aside className="setupProviderRail"><div className="gatewayRailHead"><h2>Providers</h2><p className="muted">Choose a payment method to set up.</p></div>{rows.map(x=><button key={x.gateway_id} onClick={()=>setSelected(x.code)} className={`setupProviderRow ${current?.code===x.code?'active':''}`}><div><b>{labels[x.code]||x.display_name}</b><span>{x.provider} Â· {x.environment||'built-in'}</span></div><span className={`setupBadge ${x.setup_status==='ready'?'ready':x.setup_status==='error'?'warn':'off'}`}>{x.provider==='account_credit'||x.provider==='manual'?'Built in':x.setup_status?.replaceAll('_',' ')||'not configured'}</span></button>)}</aside>

<div className="setupProviderBody">{current&&<><div className="setupHero"><div><p className="eyebrow">{current.provider}</p><h2>{labels[current.code]||current.display_name}</h2><p className="muted">{external.includes(current.provider)?'Complete each setup section, verify the provider connection, then enable it from Payments & gateways.':'This gateway is built into OrbitFS and does not require external credentials.'}</p></div><span className={`setupStateLarge ${ready?'ready':''}`}>{external.includes(current.provider)?(ready?'Ready to enable':'Setup required'):'Available'}</span></div>{external.includes(current.provider)&&<><section className="setupSection"><div className="setupSectionHead"><div><h3>1. Provider credentials</h3><p className="muted">Enter only the provider credentials. OrbitFS creates and stores the webhook credential automatically when you finish setup.</p></div></div><div className="secretGrid">{keys.map((k:any)=><div className="secretField" key={k[0]}><div className="secretFieldHead"><div><b>{k[1]}</b><span>{has(k[0])?'Stored securely':'Not configured'}</span></div><span className={`miniState ${has(k[0])?'on':'off'}`}>{has(k[0])?'Stored':'Missing'}</span></div><div className="secretInputRow"><input type="password" autoComplete="new-password" placeholder={has(k[0])?'Enter a new value to rotate':k[2]} value={form.credentials?.[k[0]]||''} onChange={e=>setForm({...form,credentials:{...form.credentials,[k[0]]:e.target.value}})}/><button onClick={()=>saveSecret(k[0])}>{has(k[0])?'Rotate':'Save'}</button>{has(k[0])&&<button className="secondary" onClick={()=>removeSecret(k[0])}>Remove</button>}</div></div>)}</div></section>

<section className="setupSection"><div className="setupSectionHead"><div><h3>2. Environment & currencies</h3><p className="muted">Control test/live mode and which invoice currencies this gateway can handle.</p></div></div><div className="setupChoiceRow"><button className={form.environment==='sandbox'?'active secondary':'secondary'} onClick={()=>setForm({...form,environment:'sandbox'})}>Sandbox / Test</button><button className={form.environment==='live'?'active secondary':'secondary'} onClick={()=>setForm({...form,environment:'live'})}>Live / Production</button></div><div className="currencyPicker">{['AUD','USD','NZD','GBP','EUR','CAD'].map(c=><button className={form.currencies.includes(c)?'active secondary':'secondary'} key={c} onClick={()=>setForm({...form,currencies:form.currencies.includes(c)?form.currencies.filter((x:string)=>x!==c):[...form.currencies,c]})}>{c}</button>)}</div><button onClick={saveSetup}>Save environment & currencies</button></section>

<section className="setupSection"><div className="setupSectionHead"><div><h3>3. Webhook & return handling</h3><p className="muted">Provider notifications settle invoices even if the customer closes the checkout tab.</p></div></div><div className="webhookCard"><div><b>Webhook endpoint</b><code>{typeof window!=='undefined'?`${window.location.origin}/api/payments/webhook/${current.provider}`:`/api/payments/webhook/${current.provider}`}</code></div><div className="inlineActions"><button className="secondary" onClick={()=>navigator.clipboard?.writeText(`${location.origin}/api/payments/webhook/${current.provider}`)}>Copy URL</button><button onClick={autoWebhook}>Register automatically</button></div></div><div className="setupChecklist compact"><div className={current.provider==='stripe'?status?.webhooks?.stripe:status?.webhooks?.paypal?'done':''}><b>Webhook signing credential</b><span>{current.provider==='stripe'?'Stripe whsec secret':'PayPal webhook ID'}</span></div><div className="done"><b>Return flow</b><span>Hosted checkout returns to OrbitFS invoice</span></div><div className="done"><b>Settlement</b><span>Successful payment triggers invoice + order provisioning</span></div></div></section>

<section className="setupSection"><div className="setupSectionHead"><div><h3>4. Verify & readiness</h3><p className="muted">OrbitFS connects to the provider using the stored credentials and records the result.</p></div><span className={`setupBadge ${ready?'ready':current.setup_status==='error'?'warn':'off'}`}>{current.setup_status?.replaceAll('_',' ')}</span></div><div className="setupChecklist"><div className={status?.serviceRole?'done':''}><b>Secure server runtime</b><span>{status?.serviceRole?'Supabase Edge + Vault ready':status?'Secure runtime unavailable':'Checking secure runtime…'}</span></div><div className={(current.provider==='stripe'?status?.stripe?.verified:status?.paypal?.verified)?'done':''}><b>Provider authentication</b><span>{(current.provider==='stripe'?status?.stripe?.error:status?.paypal?.error)||'Run verification to test credentials'}</span></div><div className={current.provider==='stripe'?(status?.webhooks?.stripe?'done':''):(status?.webhooks?.paypal?'done':'')}><b>Webhook credential</b><span>Required before production activation</span></div></div><div className="inlineActions"><button onClick={finishSetup}>Finish setup automatically</button><button className="secondary" onClick={verify}>Verify again</button><Link className="buttonlink secondary" href="/admin/payments">Continue to configuration â†’</Link></div></section></>}

{!external.includes(current.provider)&&<section className="setupSection"><h3>Built-in gateway</h3><p className="muted">No external account or API keys are required. Use the configuration page to control customer-facing labels, fees, ordering and enabled state.</p><Link className="buttonlink" href="/admin/payments">Configure gateway â†’</Link></section>}<p className="inlineStatus">{msg}</p></>}</div></section></main>}

