"use client";
import {useEffect,useMemo,useState} from "react";import Link from "next/link";import {createClient} from "@/lib/supabase";
import MailSubscriptionCategories from "@/components/MailSubscriptionCategories";
import "./outbound-mail-collapse.css";
async function json(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return {error:t}}}
export default function OutboundMail(){const sb=createClient();const [data,setData]=useState<any>(),[q,setQ]=useState(""),[cat,setCat]=useState("All"),[edit,setEdit]=useState<any>(),[msg,setMsg]=useState("");
async function token(){return (await sb.auth.getSession()).data.session?.access_token||""}async function load(){const t=await token();if(!t)return location.href="/login";const r=await fetch("/api/mail/admin",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"});const j=await json(r);if(!r.ok)return setMsg(j.error||"Could not load outbound mail settings.");setData(j)}useEffect(()=>{load()},[]);
async function saveTemplate(){if(!edit)return;setMsg("Saving template…");const t=await token();const r=await fetch("/api/mail/admin",{method:"PUT",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({action:"template",template:edit})});const j=await json(r);setMsg(r.ok?"Template saved.":j.error||"Save failed.");if(r.ok){setEdit(undefined);await load()}}
async function saveAutomation(a:any,patch:any){const next={...a,...patch};setData((d:any)=>({...d,automations:d.automations.map((x:any)=>x.event_key===a.event_key?next:x)}));const t=await token();const r=await fetch("/api/mail/admin",{method:"PUT",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({action:"automation",eventKey:next.event_key,templateKey:next.template_key,enabled:next.enabled})});const j=await json(r);setMsg(r.ok?`${next.name} automation saved.`:j.error||"Automation save failed.");if(!r.ok)await load()}
async function saveSubscription(body:any){const t=await token();const r=await fetch("/api/mail/admin",{method:"PUT",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await json(r);if(!r.ok){setMsg(j.error||"Subscription save failed.");return false}await load();setMsg("Subscription settings saved.");return true}
const categories=useMemo(()=>Array.from(new Set(((data?.templates||[]) as any[]).map(x=>String(x.category||"").trim()).filter(Boolean))).sort(),[data]);
const automationGroups=useMemo(()=>[...new Set(((data?.automations||[]) as any[]).map(a=>String(a.category||"Other")))].sort(),[data]);
function automationRow(a:any){return <details className="outboundAutomationItem" key={a.event_key}><summary><span><b>{a.name}</b><small>{a.event_key}</small></span><span className={a.enabled?"mailTemplateState on":"mailTemplateState off"}>{a.enabled?"Enabled":"Disabled"}</span></summary><div className="mailAutomationRow"><div><span>{a.description}</span><small>{(a.variables||[]).map((v:string)=>`{{${v}}}`).join(" · ")}</small></div><select value={a.template_key||""} disabled={!a.enabled} onChange={e=>saveAutomation(a,{template_key:e.target.value||null})}><option value="">No template</option>{data.templates.map((t:any)=><option value={t.template_key} key={t.template_key}>{t.name} · {t.template_key}</option>)}</select><label className="toggle compact"><input type="checkbox" checked={a.enabled} onChange={e=>saveAutomation(a,{enabled:e.target.checked})}/><span>{a.enabled?"On":"Off"}</span></label></div></details>}
const rows=useMemo(()=>((data?.templates||[]) as any[]).filter(x=>(cat==="All"||x.category===cat)&&`${x.name} ${x.template_key} ${x.subject}`.toLowerCase().includes(q.toLowerCase())),[data,q,cat]);if(!data)return <main className="adminShell">{msg||"Loading outbound mail…"}</main>;
return <main className="adminShell outboundMailPage"><header className="adminTop"><div><p className="eyebrow">SETTINGS / MAIL</p><h1>Outbound Mail</h1><p className="muted">Configure event-driven customer emails using OrbitFS Mail templates and automatic variable replacement.</p></div><Link className="buttonlink secondary" href="/mail/admin">Mail Admin</Link></header>
<div className="outboundMailOverview" style={{display:"flex",flexWrap:"wrap",gap:12,alignItems:"center",fontSize:12,margin:"10px 0 16px"}}><span><b>{data.automations?.length||0}</b> automations</span><span><b>{data.templates.length}</b> templates</span><span>{data.provider.apiKeyConfigured?"Resend configured":"Resend API key missing"}</span><span>{data.logs.length} recent deliveries</span></div>
<details className="panel outboundSettingsCollapse">
 <summary><b>Customer email subscriptions</b><small>{data.subscriptionCategories?.length||0} categories · Manage defaults and event routing</small></summary>
 <div className="outboundSettingsBody"><MailSubscriptionCategories tone="dark" categories={data.subscriptionCategories||[]} events={data.subscriptionEvents||[]} automations={data.automations||[]} templates={data.templates||[]} onSave={saveSubscription} showEvents/></div>
</details>
<details className="panel outboundSettingsCollapse">
 <summary><b>Automatic outbound emails</b><small>{data.automations?.length||0} automations · Edit the template and enabled state</small></summary>
 <div className="outboundSettingsBody"><div className="mailAutomationGroups">
  {automationGroups.map(group=><details className="outboundCategoryGroup" key={group}><summary><b>{group}</b><small>{data.automations.filter((a:any)=>String(a.category||"Other")===group).length} automations</small></summary>
   <div className="mailAutomationList">{data.automations.filter((a:any)=>String(a.category||"Other")===group).map(automationRow)}</div>
  </details>)}
 </div></div>
</details>
<details className="panel outboundSettingsCollapse">
 <summary><b>Lifecycle email templates</b><small>{data.templates.length} templates · Releases, news, deployment and transactional mail</small></summary>
 <div className="outboundSettingsBody">
  <div className="filterBar"><input placeholder="Search templates" value={q} onChange={e=>setQ(e.target.value)}/><select value={cat} onChange={e=>setCat(e.target.value)}><option>All</option>{categories.map((x:any)=><option key={x}>{x}</option>)}</select></div>
  {q.trim()||cat!=="All"?<div className="outboundTemplateList">{rows.map((t:any)=><button className="outboundTemplateRow" key={t.id} onClick={()=>setEdit({...t})}><div><b>{t.name}</b><span>{t.subject}</span><small>{t.category} · {t.template_key} · {t.from_account}</small></div><span className={`mailTemplateState ${t.enabled?"on":"off"}`}>{t.enabled?"Enabled":"Disabled"}</span></button>)}</div>:
  <div className="outboundTemplateGroups">{categories.map(group=><details className="outboundCategoryGroup" key={group}><summary><b>{group}</b><small>{data.templates.filter((t:any)=>t.category===group).length} templates</small></summary><div className="outboundTemplateList">{data.templates.filter((t:any)=>t.category===group).map((t:any)=><button className="outboundTemplateRow" key={t.id} onClick={()=>setEdit({...t})}><div><b>{t.name}</b><span>{t.subject}</span><small>{t.template_key} · {t.from_account}</small></div><span className={`mailTemplateState ${t.enabled?"on":"off"}`}>{t.enabled?"Enabled":"Disabled"}</span></button>)}</div></details>)}</div>}
 </div>
</details>
{edit&&<div className="orderModalBackdrop" onMouseDown={()=>setEdit(undefined)}><section className="orderModal outboundTemplateModal" onMouseDown={e=>e.stopPropagation()}><div className="panelTitle"><div><h2>{edit.name}</h2><p className="muted"><code>{edit.template_key}</code></p></div><button className="small secondary" onClick={()=>setEdit(undefined)}>Close</button></div><div className="form"><label>Template name<input value={edit.name||""} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>Subject<input value={edit.subject||""} onChange={e=>setEdit({...edit,subject:e.target.value})}/></label><div className="two"><label>Category<input list="mail-template-categories" value={edit.category||""} onChange={e=>setEdit({...edit,category:e.target.value})}/><datalist id="mail-template-categories">{categories.map((x:any)=><option value={x} key={x}/>)}</datalist></label><label>From account<input list="mail-template-senders" value={edit.from_account||""} onChange={e=>setEdit({...edit,from_account:e.target.value})}/><datalist id="mail-template-senders"><option value="role:system">System / notifications · {data.runtimeConfig?.outbound?.system_sender||"info@orbitfs.cc"}</option><option value="role:support">Support · {data.runtimeConfig?.outbound?.support_sender||"support@orbitfs.cc"}</option><option value="role:billing">Billing · {data.runtimeConfig?.outbound?.billing_sender||"billing@orbitfs.cc"}</option>{(data.accounts||[]).filter((a:any)=>a.active!==false).map((a:any)=><option value={a.address} key={a.address}>{a.display_name||a.address}</option>)}</datalist><small className="muted">Use a role alias to follow Mail Config automatically, or choose a specific mailbox.</small></label></div><div className="muted" style={{fontSize:12}}>Always available: <code>{"{{site_url}}"}</code> · <code>{"{{email_reference_id}}"}</code>. Event-specific variables are listed in the automation section above.</div><label className="toggle"><input type="checkbox" checked={edit.enabled!==false} onChange={e=>setEdit({...edit,enabled:e.target.checked})}/><span>Enabled</span></label><label>Plain text<textarea rows={7} value={edit.text_body||""} onChange={e=>setEdit({...edit,text_body:e.target.value})}/></label><label>HTML<textarea rows={9} value={edit.html||""} onChange={e=>setEdit({...edit,html:e.target.value})}/></label><button onClick={saveTemplate}>Save template</button></div></section></div>}{msg&&<p className="inlineStatus">{msg}</p>}</main>}
