"use client";
import {use,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase";
import InvoiceAdminTabs from "@/components/InvoiceAdminTabs";

const money=(n:any,c="AUD")=>new Intl.NumberFormat("en-AU",{style:"currency",currency:c}).format(Number(n||0)/100);

export default function InvoiceRefundPage({params}:{params:Promise<{id:string}>}){
 const {id}=use(params),sb=createClient();
 const [inv,setInv]=useState<any>(),[payments,setPayments]=useState<any[]>([]),[refunds,setRefunds]=useState<any[]>([]),[amount,setAmount]=useState(""),[method,setMethod]=useState("wallet"),[paymentId,setPaymentId]=useState(""),[reason,setReason]=useState(""),[msg,setMsg]=useState("");
 async function load(){const [i,p,r]=await Promise.all([sb.from("invoices").select("*").eq("id",id).single(),sb.from("invoice_payments").select("*").eq("invoice_id",id).eq("status","completed").order("created_at",{ascending:false}),sb.from("invoice_refunds").select("*").eq("invoice_id",id).order("created_at",{ascending:false})]);setInv(i.data);setPayments(p.data||[]);setRefunds(r.data||[]);if(!paymentId){const orig=(p.data||[]).find((x:any)=>["stripe","paypal"].includes(x.method));if(orig)setPaymentId(orig.id)}}
 useEffect(()=>{load()},[id]);
 const refunded=useMemo(()=>refunds.filter((r:any)=>["pending","processing","completed","succeeded"].includes(String(r.status||"").toLowerCase())).reduce((n:number,r:any)=>n+Number(r.amount_cents||0),0),[refunds]);
 const refundable=Math.max(0,Number(inv?.paid_cents||0)-refunded),currency=inv?.currency||"AUD";
 async function submit(){const cents=Math.round(Number(amount||0)*100);if(cents<=0)return setMsg("Enter a refund amount.");if(cents>refundable)return setMsg("Refund exceeds the remaining refundable balance.");if(!reason.trim())return setMsg("Enter a reason for the refund.");if(!confirm(`Refund ${money(cents,currency)} by ${method==='wallet'?'OrbitFS Wallet':'original payment method'}?`))return;setMsg("Processing refund…");if(method==='wallet'){const {error}=await sb.rpc("admin_refund_invoice_to_wallet",{p_invoice_id:id,p_amount_cents:cents,p_reason:reason.trim()});setMsg(error?.message||"Refund added to customer wallet.");if(!error){setAmount("");setReason("");await load()}return}const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)return setMsg("Authentication expired.");const res=await fetch("/api/admin/invoices/refund",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({invoice_id:id,payment_id:paymentId||null,amount_cents:cents,reason:reason.trim()})});const d=await res.json();setMsg(res.ok?`Refund ${d.status==="pending"?"submitted and processing":"sent"} to original ${d.method||"payment"} method.`:(d.error||"Refund failed."));if(res.ok){setAmount("");setReason("");await load()}}
 if(!inv)return <main className="adminShell">Loading refund tools…</main>;
 const originalPayments=payments.filter((p:any)=>["stripe","paypal"].includes(p.method));
 return <main className="adminShell"><header className="adminTop"><div><p className="eyebrow">INVOICE REFUND</p><h1>{inv.invoice_number}</h1><p className="muted">Refund all or part of a paid invoice to the original gateway or the customer's OrbitFS Wallet.</p></div><Link className="buttonlink secondary" href={`/admin/invoices/${id}`}>← Invoice</Link></header><InvoiceAdminTabs invoiceId={id}/><div className="adminGrid"><section className="panel"><h2>Refund balance</h2><div className="stats three"><article><small>Paid</small><strong>{money(inv.paid_cents,currency)}</strong></article><article><small>Refunded / reserved</small><strong>{money(refunded,currency)}</strong></article><article><small>Refundable</small><strong>{money(refundable,currency)}</strong></article></div><div className="form"><label>Refund destination<select value={method} onChange={e=>setMethod(e.target.value)}><option value="wallet">OrbitFS Wallet</option><option value="original" disabled={!originalPayments.length}>Original payment method</option></select><small>Wallet refunds are immediate internal credit. Original-method refunds are submitted through Stripe or PayPal and may take time to appear with the customer's bank or provider.</small></label>{method==='original'&&<label>Original payment<select value={paymentId} onChange={e=>setPaymentId(e.target.value)}>{originalPayments.map((p:any)=><option key={p.id} value={p.id}>{String(p.method).toUpperCase()} · {money(p.amount_cents,currency)} · {p.external_reference||"No reference"}</option>)}</select></label>}<label>Amount (AUD)<input type="number" min="0.01" step="0.01" max={(refundable/100).toFixed(2)} value={amount} onChange={e=>setAmount(e.target.value)} placeholder={(refundable/100).toFixed(2)}/></label><label>Reason<textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for refund"/></label><button type="button" disabled={refundable<=0||!amount||!reason.trim()||(method==='original'&&!paymentId)} onClick={submit}>Process refund</button>{msg&&<span>{msg}</span>}</div></section><section className="panel"><div className="panelTitle"><h2>Refund history</h2><span>{refunds.length}</span></div>{refunds.length?refunds.map((r:any)=><div className="adminItem" key={r.id}><div><b>{money(r.amount_cents,currency)} · {String(r.method).replaceAll("_"," ")}</b><span>{r.reason||"No reason"} · {new Date(r.created_at).toLocaleString()}</span></div><span>{r.status}</span></div>):<p className="muted">No refunds recorded for this invoice.</p>}</section></div></main>;
}
