-- Restore transactional lifecycle mail templates/automation mappings that are emitted
-- by the live order, invoice, service, cancellation and refund workflows.
-- Existing customized rows are preserved.

insert into public.mail_templates
  (template_key,name,category,subject,html,text_body,from_account,enabled)
values
  ('customer.created','Customer welcome','account','Welcome to OrbitFS','<p>Hi {{customer_name}},</p><p>Your OrbitFS account is ready.</p><p><a href="{{site_url}}">Open OrbitFS</a></p>','Hi {{customer_name}},\n\nYour OrbitFS account is ready.\n\n{{site_url}}','noreply@orbitfs.cc',true),
  ('order.created','Order created','orders','OrbitFS order {{order_number}} received','<p>Hi {{customer_name}},</p><p>We received order <strong>{{order_number}}</strong>.</p><p>Total: {{order_total}}</p>','Hi {{customer_name}},\n\nWe received order {{order_number}}.\nTotal: {{order_total}}','noreply@orbitfs.cc',true),
  ('order.paid','Order paid','orders','Payment received for OrbitFS order {{order_number}}','<p>Hi {{customer_name}},</p><p>Payment has been received for order <strong>{{order_number}}</strong>.</p><p>Total: {{order_total}}</p>','Hi {{customer_name}},\n\nPayment has been received for order {{order_number}}.\nTotal: {{order_total}}','noreply@orbitfs.cc',true),
  ('service.activated','Service activated','service','Your OrbitFS service is active','<p>Hi {{customer_name}},</p><p>Your OrbitFS service for order <strong>{{order_number}}</strong> is active.</p>','Hi {{customer_name}},\n\nYour OrbitFS service for order {{order_number}} is active.','noreply@orbitfs.cc',true),
  ('service.suspended','Service suspended','service','Your OrbitFS service is suspended','<p>Hi {{customer_name}},</p><p>Your OrbitFS service for order <strong>{{order_number}}</strong> has been suspended.</p><p>{{reason}}</p>','Hi {{customer_name}},\n\nYour OrbitFS service for order {{order_number}} has been suspended.\n{{reason}}','noreply@orbitfs.cc',true),
  ('service.restored','Service restored','service','Your OrbitFS service has been restored','<p>Hi {{customer_name}},</p><p>Your OrbitFS service for order <strong>{{order_number}}</strong> has been restored.</p>','Hi {{customer_name}},\n\nYour OrbitFS service for order {{order_number}} has been restored.','noreply@orbitfs.cc',true),
  ('service.terminated','Service terminated','service','Your OrbitFS service has been terminated','<p>Hi {{customer_name}},</p><p>Your OrbitFS service for order <strong>{{order_number}}</strong> has been terminated.</p><p>{{reason}}</p>','Hi {{customer_name}},\n\nYour OrbitFS service for order {{order_number}} has been terminated.\n{{reason}}','noreply@orbitfs.cc',true),
  ('invoice.created','Invoice created','billing','OrbitFS invoice {{invoice_number}}','<p>Hi {{customer_name}},</p><p>Invoice <strong>{{invoice_number}}</strong> has been created.</p><p>Total: {{invoice_total}}</p><p>Due: {{invoice_due}} by {{due_date}}</p><p><a href="{{invoice_url}}">View invoice</a></p>','Hi {{customer_name}},\n\nInvoice {{invoice_number}} has been created.\nTotal: {{invoice_total}}\nDue: {{invoice_due}} by {{due_date}}\n\n{{invoice_url}}','billing@orbitfs.cc',true),
  ('invoice.paid','Invoice paid','billing','Payment received for invoice {{invoice_number}}','<p>Hi {{customer_name}},</p><p>Invoice <strong>{{invoice_number}}</strong> has been paid.</p><p>Total: {{invoice_total}}</p><p><a href="{{invoice_url}}">View invoice</a></p>','Hi {{customer_name}},\n\nInvoice {{invoice_number}} has been paid.\nTotal: {{invoice_total}}\n\n{{invoice_url}}','billing@orbitfs.cc',true),
  ('invoice.due','Invoice due reminder','billing','Invoice {{invoice_number}} is due soon','<p>Hi {{customer_name}},</p><p>Invoice <strong>{{invoice_number}}</strong> is due on {{due_date}}.</p><p>Amount due: {{invoice_due}}</p><p><a href="{{invoice_url}}">View invoice</a></p>','Hi {{customer_name}},\n\nInvoice {{invoice_number}} is due on {{due_date}}.\nAmount due: {{invoice_due}}\n\n{{invoice_url}}','billing@orbitfs.cc',true),
  ('invoice.overdue','Invoice overdue','billing','Invoice {{invoice_number}} is overdue','<p>Hi {{customer_name}},</p><p>Invoice <strong>{{invoice_number}}</strong> is overdue.</p><p>Amount due: {{invoice_due}}</p><p><a href="{{invoice_url}}">View invoice</a></p>','Hi {{customer_name}},\n\nInvoice {{invoice_number}} is overdue.\nAmount due: {{invoice_due}}\n\n{{invoice_url}}','billing@orbitfs.cc',true),
  ('invoice.cancelled','Invoice cancelled','billing','Invoice {{invoice_number}} cancelled','<p>Hi {{customer_name}},</p><p>Invoice <strong>{{invoice_number}}</strong> has been cancelled.</p>','Hi {{customer_name}},\n\nInvoice {{invoice_number}} has been cancelled.','billing@orbitfs.cc',true),
  ('order.cancelled_unpaid','Unpaid order cancelled','orders','OrbitFS order {{order_number}} cancelled','<p>Hi {{customer_name}},</p><p>Order <strong>{{order_number}}</strong> was cancelled because payment was not completed within the payment window.</p>','Hi {{customer_name}},\n\nOrder {{order_number}} was cancelled because payment was not completed within the payment window.','billing@orbitfs.cc',true),
  ('cancellation.requested','Cancellation requested','orders','Cancellation request received for {{order_number}}','<p>Hi {{customer_name}},</p><p>We received your cancellation request for order <strong>{{order_number}}</strong>.</p><p>Reason: {{reason}}</p>','Hi {{customer_name}},\n\nWe received your cancellation request for order {{order_number}}.\nReason: {{reason}}','noreply@orbitfs.cc',true),
  ('cancellation.scheduled','Cancellation scheduled','orders','Cancellation scheduled for {{order_number}}','<p>Hi {{customer_name}},</p><p>Cancellation for order <strong>{{order_number}}</strong> is scheduled for {{scheduled_for}}.</p><p>{{staff_note}}</p>','Hi {{customer_name}},\n\nCancellation for order {{order_number}} is scheduled for {{scheduled_for}}.\n{{staff_note}}','noreply@orbitfs.cc',true),
  ('cancellation.denied','Cancellation denied','orders','Cancellation request update for {{order_number}}','<p>Hi {{customer_name}},</p><p>The cancellation request for order <strong>{{order_number}}</strong> was not approved.</p><p>{{staff_note}}</p>','Hi {{customer_name}},\n\nThe cancellation request for order {{order_number}} was not approved.\n{{staff_note}}','noreply@orbitfs.cc',true),
  ('cancellation.completed','Cancellation completed','orders','Cancellation completed for {{order_number}}','<p>Hi {{customer_name}},</p><p>Cancellation for order <strong>{{order_number}}</strong> is complete.</p>','Hi {{customer_name}},\n\nCancellation for order {{order_number}} is complete.','noreply@orbitfs.cc',true),
  ('invoice.refund','Invoice refund','billing','Refund update for invoice {{invoice_number}}','<p>Hi {{customer_name}},</p><p>A refund for invoice <strong>{{invoice_number}}</strong> has been updated.</p><p>Amount: {{refund_amount}}</p><p>Method: {{refund_method}}</p><p>Status: {{refund_status}}</p><p>Reference: {{refund_reference}}</p><p>{{refund_timing}}</p>','Hi {{customer_name}},\n\nRefund update for invoice {{invoice_number}}.\nAmount: {{refund_amount}}\nMethod: {{refund_method}}\nStatus: {{refund_status}}\nReference: {{refund_reference}}\n{{refund_timing}}','billing@orbitfs.cc',true)
on conflict (template_key) do nothing;

insert into public.mail_automations
  (event_key,name,category,description,template_key,enabled,variables)
values
  ('customer.created','Customer welcome','account','Send a welcome message when a customer account is created.','customer.created',true,'["customer_name"]'::jsonb),
  ('order.created','Order created','orders','Notify the customer when an order is created.','order.created',true,'["customer_name","order_number","order_total"]'::jsonb),
  ('order.paid','Order paid','orders','Notify the customer when an order is paid.','order.paid',true,'["customer_name","order_number","order_total"]'::jsonb),
  ('service.activated','Service activated','service','Notify the customer when service becomes active.','service.activated',true,'["customer_name","order_number","order_total"]'::jsonb),
  ('service.suspended','Service suspended','service','Notify the customer when service is suspended.','service.suspended',true,'["customer_name","order_number","reason"]'::jsonb),
  ('service.restored','Service restored','service','Notify the customer when service is restored.','service.restored',true,'["customer_name","order_number"]'::jsonb),
  ('service.terminated','Service terminated','service','Notify the customer when service is terminated.','service.terminated',true,'["customer_name","order_number","reason"]'::jsonb),
  ('invoice.created','Invoice created','billing','Notify the customer when an invoice is created.','invoice.created',true,'["customer_name","invoice_number","invoice_total","invoice_due","due_date","invoice_url"]'::jsonb),
  ('invoice.paid','Invoice paid','billing','Notify the customer when an invoice is paid.','invoice.paid',true,'["customer_name","invoice_number","invoice_total","invoice_url"]'::jsonb),
  ('invoice.due','Invoice due reminder','billing','Remind the customer before an invoice is due.','invoice.due',true,'["customer_name","invoice_number","invoice_due","due_date","invoice_url"]'::jsonb),
  ('invoice.overdue','Invoice overdue','billing','Notify the customer when an invoice is overdue.','invoice.overdue',true,'["customer_name","invoice_number","invoice_due","invoice_url"]'::jsonb),
  ('invoice.cancelled','Invoice cancelled','billing','Notify the customer when an invoice is cancelled.','invoice.cancelled',true,'["customer_name","invoice_number"]'::jsonb),
  ('order.cancelled_unpaid','Unpaid order cancelled','orders','Notify the customer when an unpaid order is automatically cancelled.','order.cancelled_unpaid',true,'["customer_name","order_number","order_total","reason"]'::jsonb),
  ('cancellation.requested','Cancellation requested','orders','Confirm a cancellation request.','cancellation.requested',true,'["customer_name","order_number","reason"]'::jsonb),
  ('cancellation.scheduled','Cancellation scheduled','orders','Notify the customer when cancellation is scheduled.','cancellation.scheduled',true,'["customer_name","order_number","scheduled_for","staff_note"]'::jsonb),
  ('cancellation.denied','Cancellation denied','orders','Notify the customer when a cancellation request is denied.','cancellation.denied',true,'["customer_name","order_number","staff_note"]'::jsonb),
  ('cancellation.completed','Cancellation completed','orders','Notify the customer when cancellation is complete.','cancellation.completed',true,'["customer_name","order_number"]'::jsonb),
  ('invoice.refund','Invoice refund','billing','Notify the customer about invoice refund progress.','invoice.refund',true,'["customer_name","invoice_number","refund_amount","refund_method","refund_status","refund_reference","refund_timing"]'::jsonb)
on conflict (event_key) do nothing;
