"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {createClient} from "@/lib/supabase";
const blank=()=>({existing_user_id:"",first_name:"",last_name:"",email:"",title:"",staff_notes:"",status:"active",group_ids:[] as string[],primary_group_id:"",department_ids:[] as string[],primary_department_id:""});
export default function StaffMembers(){
 const sb=createClient();const [data,setData]=useState<any>({members:[],groups:[],availableCustomers:[],can:{}}),[form,setForm]=useState<any>(blank()),[editing,setEditing]=useState<any>(null),[q,setQ]=useState(""),[status,setStatus]=useState("all"),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 async function authHeaders():Promise<Record<string,string>>{const {data:{session}}=await sb.auth.getSession();return session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{}}
 async function load(){setLoading(true);const headers=await authHeaders();const r=await fetch("/api/admin/staff",{headers,cache:"no-store"});const j=await r.json().catch(()=>({}));setLoading(false);if(!r.ok){setMsg(j.error||"Unable to load Staff System.");return}setData(j)}
 useEffect(()=>{load()},[]);
 const members=data.members||[],groups=data.groups||[],departments=data.departments||[],can=data.can||{};
 const filtered=useMemo(()=>members.filter((m:any)=>{const text=`${m.display_name||""} ${m.email||""} ${m.title||""} ${(m.department_names||[]).join(" ")} ${(m.group_names||[]).join(" ")} ${m.customer_number||""}`.toLowerCase();return(!q.trim()||text.includes(q.toLowerCase()))&&(status==="all"||m.status===status)}),[members,q,status]);
 const stats={active:members.filter((m:any)=>m.status==="active").length,disabled:members.filter((m:any)=>m.status==="disabled").length,customers:members.filter((m:any)=>m.is_customer).length,groups:groups.length};
 function toggle(obj:any,setter:(v:any)=>void,id:string){const ids:Array<string>=obj.group_ids||[],next=ids.includes(id)?ids.filter(x=>x!==id):[...ids,id];setter({...obj,group_ids:next,primary_group_id:next.includes(obj.primary_group_id)?obj.primary_group_id:(next[0]||"")})}
 function edit(m:any){setEditing({...m,group_ids:[...(m.group_ids||[])],primary_group_id:m.primary_group_id||m.group_ids?.[0]||"",department_ids:[...(m.department_ids||[])],primary_department_id:m.primary_department_id||m.department_ids?.[0]||""});setMsg("")}
 async function post(body:any){setSaving(true);setMsg("");const headers=await authHeaders();const r=await fetch("/api/admin/staff",{method:"POST",headers:{...headers,"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){setMsg(j.error||"Staff operation failed.");return false}return true}
 async function add(){if(!can.invite)return setMsg("Your staff group cannot add or invite staff.");if(!form.group_ids.length)return setMsg("Choose at least one staff group.");const ok=await post({action:"member.save",...form});if(ok){setForm(blank());setMsg(form.existing_user_id?"Customer added to Staff System.":"Staff invitation sent and access created.");await load()}}
 async function saveEdit(){if(!editing||!can.manage)return;if(!editing.group_ids.length)return setMsg("Staff member needs at least one group.");const ok=await post({action:"member.save",...editing,existing_user_id:editing.user_id});if(ok){setEditing(null);setMsg("Staff member updated.");await load()}}
 async function remove(){if(!editing||!can.manage)return;if(!confirm(`Remove staff access for ${editing.display_name}? Their customer account, orders, invoices and licences will remain.`))return;const ok=await post({action:"member.remove",user_id:editing.user_id});if(ok){setEditing(null);setMsg("Staff access removed. Customer data was preserved.");await load()}}
 function Picker({obj,setter}:{obj:any,setter:(v:any)=>void}){return <div className="staffPicker">{groups.map((g:any)=>{const superGroup=g.slug==="superadmin",blocked=superGroup&&!can.permissionAdmin;return <label key={g.id} title={blocked?"Only a permission administrator can assign Superadmin.":""}><input type="checkbox" checked={(obj.group_ids||[]).includes(g.id)} disabled={blocked} onChange={()=>toggle(obj,setter,g.id)}/><span><b>{g.name}</b><small>{g.description||`${g.slug} staff group`}{superGroup?" · Protected":""}</small></span></label>})}</div>}
 function toggleDepartment(obj:any,setter:(v:any)=>void,id:string){const ids:Array<string>=obj.department_ids||[],next=ids.includes(id)?ids.filter(x=>x!==id):[...ids,id];setter({...obj,department_ids:next,primary_department_id:next.includes(obj.primary_department_id)?obj.primary_department_id:(next[0]||"")})}
 function DepartmentPicker({obj,setter}:{obj:any,setter:(v:any)=>void}){return <div className="staffPicker departmentPicker">{departments.map((d:any)=><label key={d.id}><input type="checkbox" checked={(obj.department_ids||[]).includes(d.id)} onChange={()=>toggleDepartment(obj,setter,d.id)}/><span><b>{d.name}</b><small>{d.description||"Support ticket department"}</small></span></label>)}</div>}
 if(loading)return <main className="adminShell"><div className="adminGate">Loading Staff System…</div></main>;
 return <main className="adminShell staffSystemV2"><header className="staffSystemHeader"><div><p className="eyebrow">STAFF SYSTEM</p><h1>Manage Staff Members</h1><p className="muted">Staff access is separate from customer access. Changing or removing staff access does not remove customer billing, licences or account history.</p></div><div className="staffSystemHeaderActions"><Link href="/admin/settings/staff">Overview</Link>{can.groupsView&&<Link href="/admin/settings/staff/groups">Groups & permissions</Link>}</div></header>
 <section className="staffSystemStats"><article><small>Active staff</small><strong>{stats.active}</strong></article><article><small>Disabled</small><strong>{stats.disabled}</strong></article><article><small>Also customers</small><strong>{stats.customers}</strong></article><article><small>Staff groups</small><strong>{stats.groups}</strong></article></section>
 <div className="staffWorkspace">
  <section className="panel staffCreateCard"><div className="staffCardHead"><div><h2>Add staff member</h2><p className="muted">Promote an existing customer or invite a new staff-only user.</p></div></div>{!can.invite?<div className="staffPermissionNote">You can view staff, but your group does not have <code>staff.invite</code>.</div>:<div className="staffForm"><label>Existing customer<select value={form.existing_user_id} onChange={e=>setForm({...form,existing_user_id:e.target.value})}><option value="">Invite a new staff user</option>{(data.availableCustomers||[]).map((c:any)=><option key={c.auth_user_id} value={c.auth_user_id}>{c.customer_number?`${c.customer_number} · `:""}{c.name||c.email} · {c.email}</option>)}</select></label>{!form.existing_user_id&&<><div className="two"><label>First name<input value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Last name<input value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label></div><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></>}<div className="two"><label>Staff title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Support Agent"/></label><label>Primary department<select value={form.primary_department_id} onChange={e=>{const id=e.target.value;setForm({...form,primary_department_id:id,department_ids:id&&!form.department_ids.includes(id)?[...form.department_ids,id]:form.department_ids})}}><option value="">No support department</option>{departments.map((d:any)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><label>Support departments<DepartmentPicker obj={form} setter={setForm}/><small>Staff can belong to multiple ticket departments.</small></label><label>Staff groups<Picker obj={form} setter={setForm}/></label>{form.group_ids.length>1&&<label>Primary group<select value={form.primary_group_id} onChange={e=>setForm({...form,primary_group_id:e.target.value})}>{groups.filter((g:any)=>form.group_ids.includes(g.id)).map((g:any)=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>}<label>Private staff notes<textarea rows={3} value={form.staff_notes} onChange={e=>setForm({...form,staff_notes:e.target.value})}/></label><button onClick={add} disabled={saving||!form.group_ids.length||(!form.existing_user_id&&(!form.email.trim()||!form.first_name.trim()||!form.last_name.trim()))}>{saving?"Saving…":form.existing_user_id?"Add customer as staff":"Invite staff member"}</button></div>}</section>
  <section className="panel staffMemberPanel"><div className="staffCardHead"><div><h2>Staff directory</h2><p className="muted">{members.length} staff account{members.length===1?"":"s"} · effective access is inherited from every assigned group.</p></div></div><div className="staffToolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, email, customer ID, title or group…"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All staff</option><option value="active">Active only</option><option value="disabled">Disabled only</option></select></div><div className="staffMemberRows">{filtered.length?filtered.map((m:any)=><article className="staffMemberRow" key={m.user_id}><div className="staffIdentity"><b>{m.display_name||m.email||m.user_id}</b><span>{m.email||"No customer email linked"}</span><small>{m.customer_number|| (m.is_customer?"Customer account":"Staff-only account")}</small></div><div className="staffRoleSummary"><b>{(m.group_names||[]).join(" + ")||"No group"}</b><span>{m.effective_permissions?.includes("all")?"Full authority":`${(m.effective_permissions||[]).filter((x:string)=>x!=="all").length} effective permissions`}</span><small>{m.profile_role?`Primary role: ${m.profile_role}`:""}</small></div><div className="staffMetaSummary"><b>{m.title||"Staff member"}</b><span>{(m.department_names||[]).join(", ")||"No support departments"}</span><small>{m.is_customer?"Customer + staff":"Staff-only"}</small><span className={`staffStatusPill ${m.status}`}>{m.status}</span></div><div className="staffMemberActions">{can.manage?<button className="secondary" onClick={()=>edit(m)}>Manage</button>:<button className="secondary" disabled>View only</button>}</div></article>):<div className="staffEmpty">No staff match this filter.</div>}</div></section>
 </div>
 {editing&&<div className="orderModalBackdrop" onMouseDown={()=>setEditing(null)}><section className="orderModal staffManageModal" onMouseDown={e=>e.stopPropagation()}><div className="staffCardHead"><div><h2>{editing.display_name}</h2><p className="muted">{editing.email||editing.user_id} {editing.customer_number?`· ${editing.customer_number}`:""}</p></div><button className="small secondary" onClick={()=>setEditing(null)}>Close</button></div><div className="staffForm"><div className="two"><label>Title<input value={editing.title||""} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Primary department<select value={editing.primary_department_id||""} onChange={e=>{const id=e.target.value;setEditing({...editing,primary_department_id:id,department_ids:id&&!(editing.department_ids||[]).includes(id)?[...(editing.department_ids||[]),id]:(editing.department_ids||[])})}}><option value="">No support department</option>{departments.map((d:any)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><label>Support departments<DepartmentPicker obj={editing} setter={setEditing}/></label><label>Staff access<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option value="active">Active</option><option value="disabled">Disabled</option></select></label><label>Assigned groups<Picker obj={editing} setter={setEditing}/></label>{editing.group_ids.length>1&&<label>Primary group<select value={editing.primary_group_id} onChange={e=>setEditing({...editing,primary_group_id:e.target.value})}>{groups.filter((g:any)=>editing.group_ids.includes(g.id)).map((g:any)=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>}<label>Private staff notes<textarea rows={4} value={editing.staff_notes||""} onChange={e=>setEditing({...editing,staff_notes:e.target.value})}/></label><button onClick={saveEdit} disabled={saving||!editing.group_ids.length}>{saving?"Saving…":"Save staff member"}</button><div className="staffDangerZone"><span>Removing staff access does not delete the customer account or any customer data.</span><button className="danger" onClick={remove} disabled={saving}>Remove staff access</button></div></div></section></div>}
 {msg&&<div className="staffSystemMessage">{msg}</div>}
 </main>
}
