"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {createClient} from "@/lib/supabase";import {CAP as BASE_CAP} from "@/lib/staff-capabilities";import {SUPPORT_CAP} from "@/lib/support-capabilities";import {ALERT_CAP} from "@/lib/alert-capabilities";
const CAP:Record<string,[string,string,string]>={...BASE_CAP,...SUPPORT_CAP,...ALERT_CAP};
export default function StaffGroups(){
 const sb=createClient();const [data,setData]=useState<any>({groups:[],members:[],can:{}}),[selected,setSelected]=useState(""),[draft,setDraft]=useState<any>(null),[q,setQ]=useState(""),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[newName,setNewName]=useState(""),[newDesc,setNewDesc]=useState("");
 async function headers():Promise<Record<string,string>>{const {data:{session}}=await sb.auth.getSession();return session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{}}
 async function load(prefer?:string){setLoading(true);const h=await headers();const r=await fetch("/api/admin/staff",{headers:h,cache:"no-store"});const j=await r.json().catch(()=>({}));setLoading(false);if(!r.ok){setMsg(j.error||"Unable to load staff groups.");return}setData(j);const id=prefer||selected||j.groups?.[0]?.id||"";setSelected(id);setDraft(j.groups?.find((x:any)=>x.id===id)||null)}
 useEffect(()=>{load()},[]);
 const groups=data.groups||[],members=data.members||[],can=data.can||{},keys=Object.keys(CAP);
 const sections=[...new Set(keys.map(k=>CAP[k][2]))];
 function choose(g:any){setSelected(g.id);setDraft({...g,permissions:{...(g.permissions||{})}});setMsg("")}
 function toggle(k:string,v:boolean){if(!draft||draft.slug==="superadmin"||!can.groupsManage)return;setDraft({...draft,permissions:{...(draft.permissions||{}),[k]:v}})}
 function setSection(section:string,v:boolean){if(!draft||draft.slug==="superadmin"||!can.groupsManage)return;const p={...(draft.permissions||{})};keys.filter(k=>CAP[k][2]===section&&k!=="all").forEach(k=>p[k]=v);setDraft({...draft,permissions:p})}
 async function post(body:any){setSaving(true);setMsg("");const h=await headers();const r=await fetch("/api/admin/staff",{method:"POST",headers:{...h,"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){setMsg(j.error||"Staff group operation failed.");return null}return j}
 async function save(){if(!draft||!can.groupsManage)return;const j=await post({action:"group.save",group_id:draft.id,name:draft.name,description:draft.description,permissions:draft.permissions});if(j){setMsg(`${draft.name} saved.`);await load(draft.id)}}
 async function create(){if(!can.groupsManage)return;const name=newName.trim();if(!name)return setMsg("Group name is required.");const j=await post({action:"group.create",name,description:newDesc,permissions:{"admin.access":true}});if(j?.group){setNewName("");setNewDesc("");(document.getElementById("newStaffGroupV2") as HTMLDialogElement)?.close();setMsg("Staff group created.");await load(j.group.id)}}
 async function remove(){if(!draft||draft.is_system||!can.groupsManage)return;if(!confirm(`Delete ${draft.name}? Assigned staff must be moved first.`))return;const j=await post({action:"group.delete",group_id:draft.id});if(j){setSelected("");setDraft(null);setMsg("Staff group deleted.");await load()}}
 const visibleSections=sections.map(section=>({section,items:keys.filter(k=>CAP[k][2]===section&&k!=="all"&&(!q.trim()||`${CAP[k][0]} ${CAP[k][1]} ${k}`.toLowerCase().includes(q.toLowerCase())))})).filter(x=>x.items.length);
 const groupCount=(id:string)=>members.filter((m:any)=>(m.group_ids||[]).includes(id)).length;
 const enabled=draft?.slug==="superadmin"?keys.length:keys.filter(k=>k!=="all"&&!!draft?.permissions?.[k]).length;
 if(loading)return <main className="adminShell"><div className="adminGate">Loading staff groups…</div></main>;
 return <main className="adminShell staffSystemV2"><header className="staffSystemHeader"><div><p className="eyebrow">STAFF SYSTEM</p><h1>Groups & Permissions</h1><p className="muted">Every staff member can inherit access from multiple groups. Changes here affect permission checks across the Admin Center.</p></div><div className="staffSystemHeaderActions"><Link href="/admin/settings/staff">Overview</Link><Link href="/admin/settings/staff/members">Staff members</Link></div></header>
 {!can.groupsManage&&<div className="staffPermissionNote">View-only mode. Your staff group has <code>staff.groups.view</code> but not <code>staff.groups.manage</code>.</div>}
 <div className="staffGroupWorkspaceV2"><aside className="staffGroupRailV2"><div className="staffGroupRailHeader"><b>Staff groups</b>{can.groupsManage&&<button className="small" onClick={()=>(document.getElementById("newStaffGroupV2") as HTMLDialogElement)?.showModal()}>+ New</button>}</div>{groups.map((g:any)=>{const count=g.slug==="superadmin"?keys.length:keys.filter(k=>k!=="all"&&!!g.permissions?.[k]).length;return <button key={g.id} className={g.id===selected?"active":""} onClick={()=>choose(g)}><span><b>{g.name}</b><small>{groupCount(g.id)} member{groupCount(g.id)===1?"":"s"} · {g.is_system?"System":"Custom"} · {count} permissions</small></span>{g.slug==="superadmin"&&<em>FULL</em>}</button>})}</aside>
 {draft&&<section className="panel staffGroupEditorV2"><div className="staffGroupEditorTop"><div className="staffGroupIdentityV2"><input value={draft.name||""} disabled={!can.groupsManage||draft.slug==="superadmin"} onChange={e=>setDraft({...draft,name:e.target.value})}/><input value={draft.description||""} disabled={!can.groupsManage} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Group description"/><small><code>{draft.slug}</code> · {draft.is_system?"protected system group":"custom group"} · {groupCount(draft.id)} assigned member{groupCount(draft.id)===1?"":"s"}</small></div>{can.groupsManage&&<div className="inlineActions"><button onClick={save} disabled={saving}>{saving?"Saving…":"Save group"}</button>{!draft.is_system&&<button className="danger" onClick={remove} disabled={saving}>Delete</button>}</div>}</div>
 {draft.slug==="superadmin"?<div className="staffSuperadminBanner"><div><b>Full system authority</b><span>Superadmin always receives every current and future permission through <code>all</code>. Individual capabilities cannot be disabled.</span></div><strong>ALL PERMISSIONS</strong></div>:<div className="staffPermissionSearchV2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search capability, description or permission key…"/><span>{enabled}/{keys.length-1} enabled</span></div>}
 <div>{visibleSections.map(({section,items})=><details className="staffPermissionSectionV2" key={section} open={!!q||section==="Access"||section==="Staff System"||section==="Support"||section==="OrbitFS Alert System"}><summary><span><b>{section}</b><small>{items.filter(k=>draft.slug==="superadmin"||!!draft.permissions?.[k]).length}/{items.length} enabled</small></span>{can.groupsManage&&draft.slug!=="superadmin"&&<div className="staffPermissionBulkV2" onClick={e=>e.preventDefault()}><button type="button" className="small secondary" onClick={()=>setSection(section,true)}>All</button><button type="button" className="small secondary" onClick={()=>setSection(section,false)}>None</button></div>}</summary><div className="staffPermissionGridV2">{items.map(k=>{const [label,description]=CAP[k],on=draft.slug==="superadmin"||!!draft.permissions?.[k];return <label className={`staffPermissionItemV2 ${on?"on":""}`} key={k}><input type="checkbox" checked={on} disabled={!can.groupsManage||draft.slug==="superadmin"} onChange={e=>toggle(k,e.target.checked)}/><span><b>{label}</b><small>{description}</small><code>{k}</code></span></label>})}</div></details>)}</div></section>}
 </div>
 <dialog id="newStaffGroupV2" className="staffGroupDialogV2"><div className="form"><h2>Create staff group</h2><p className="muted">New groups start with Admin Center access only. Add the exact capabilities they need after creation.</p><label>Name<input value={newName} onChange={e=>setNewName(e.target.value)}/></label><label>Description<input value={newDesc} onChange={e=>setNewDesc(e.target.value)}/></label><div className="inlineActions"><button onClick={create} disabled={saving}>{saving?"Creating…":"Create group"}</button><button className="secondary" onClick={()=>(document.getElementById("newStaffGroupV2") as HTMLDialogElement)?.close()}>Cancel</button></div></div></dialog>
 {msg&&<div className="staffSystemMessage">{msg}</div>}
 </main>
}
