"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase";
import {usePermissions} from "@/lib/usePermissions";

const pretty=(s:string)=>String(s||"").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase());
const invoiceDue=(i:any)=>Math.max(0,Number(i.total_cents||0)-Number(i.paid_cents||0));
function ageLabel(value?:string|null){
 if(!value)return "—";
 const ms=Math.max(0,Date.now()-new Date(value).getTime()),h=Math.floor(ms/3600000),d=Math.floor(h/24);
 return d>0?`${d}d`:h>0?`${h}h`:`${Math.max(1,Math.floor(ms/60000))}m`;
}

type AttentionItem={key:string;kind:"invoice"|"ticket"|"order"|"cancel";rank:number;href:string;record:string;subject:string;customer:string;state:string;amount:number|null;when:string|null;urgent:boolean};

export default function Admin(){
 const sb=createClient(),{can}=usePermissions();
 const [users,setUsers]=useState<any[]>([]),[tickets,setTickets]=useState<any[]>([]),[orders,setOrders]=useState<any[]>([]),[invoices,setInvoices]=useState<any[]>([]),[balances,setBalances]=useState<any[]>([]),[cancellations,setCancellations]=useState<any>({pending_count:0,scheduled_count:0}),[me,setMe]=useState<string>();

 async function load(){
  const {data:{user}}=await sb.auth.getUser();setMe(user?.id);const jobs:any[]=[];
  jobs.push(can("customers.view")?sb.from("user_profiles").select("*").order("created_at",{ascending:false}):Promise.resolve({data:[]}));
  jobs.push(can("support.manage")?sb.from("support_tickets").select("*,support_departments(name)").order("updated_at",{ascending:false}):Promise.resolve({data:[]}));
  jobs.push(can("orders.view")?sb.from("orders").select("*").order("created_at",{ascending:false}).limit(50):Promise.resolve({data:[]}));
  jobs.push(can("invoices.view")?sb.from("invoices").select("*").order("created_at",{ascending:false}).limit(80):Promise.resolve({data:[]}));
  jobs.push(can("customers.view")?sb.from("account_balances").select("*"):Promise.resolve({data:[]}));
  jobs.push(can("customers.cancellations")?sb.rpc("admin_cancellation_queue_snapshot"):Promise.resolve({data:{pending_count:0,scheduled_count:0}}));
  const [u,t,o,i,b,c]=await Promise.all(jobs);setUsers(u.data||[]);setTickets(t.data||[]);setOrders(o.data||[]);setInvoices(i.data||[]);setBalances(b.data||[]);setCancellations(c.data||{pending_count:0,scheduled_count:0});
 }
 useEffect(()=>{load()},[can]);

 const activeTickets=tickets.filter(t=>!t.archived_at&&t.status!=="closed"),newTickets=activeTickets.filter(t=>t.status==="open"&&!t.assigned_to),staffReply=activeTickets.filter(t=>t.status==="staff_reply"),customerReply=activeTickets.filter(t=>t.status==="customer_reply"),mine=activeTickets.filter(t=>t.assigned_to===me);
 const queue=useMemo(()=>activeTickets.slice().sort((a,b)=>{const rank=(x:any)=>x.status==="staff_reply"?0:(!x.assigned_to&&x.status==="open")?1:x.priority==="urgent"?2:x.priority==="high"?3:x.status==="pending"?4:x.status==="on_hold"?5:6;return rank(a)-rank(b)||+new Date(b.updated_at)-+new Date(a.updated_at)}).slice(0,7),[tickets,me]);
 const unpaidInvoices=invoices.filter(i=>!["paid","void","cancelled","refunded"].includes(i.status)&&invoiceDue(i)>0),outstanding=unpaidInvoices.reduce((a,i)=>a+invoiceDue(i),0),overdue=unpaidInvoices.filter(i=>i.due_at&&new Date(i.due_at).getTime()<Date.now());
 const waitingOrders=orders.filter(o=>["pending_payment","pending_approval"].includes(o.status)||["pending","unfulfilled"].includes(o.fulfillment_status));
 const pendingCancellations=Number(cancellations.pending_count||0),attentionTotal=unpaidInvoices.length+newTickets.length+staffReply.length+waitingOrders.length+pendingCancellations;
 const owner=(id:string)=>users.find(s=>s.id===id)?.display_name||"Unassigned";
 const customerName=(row:any)=>row?.customer_name||row?.customer?.display_name||users.find(u=>u.id===(row?.user_id||row?.customer_id||row?.customer_user_id))?.display_name||"Customer";

 const attentionItems=useMemo<AttentionItem[]>(()=>{
  const items:AttentionItem[]=[];
  unpaidInvoices.forEach(i=>{const isOverdue=!!i.due_at&&new Date(i.due_at).getTime()<Date.now();items.push({key:`invoice-${i.id}`,kind:"invoice",rank:isOverdue?0:3,href:`/admin/invoices/${i.id}`,record:i.invoice_number||"Invoice",subject:isOverdue?"Payment overdue":"Payment outstanding",customer:customerName(i),state:isOverdue?"Overdue":pretty(i.status),amount:invoiceDue(i),when:i.due_at||i.created_at,urgent:isOverdue})});
  activeTickets.filter(t=>t.status==="staff_reply"||(!t.assigned_to&&t.status==="open")||["urgent","high"].includes(t.priority)).forEach(t=>items.push({key:`ticket-${t.id}`,kind:"ticket",rank:t.status==="staff_reply"?1:2,href:`/admin/support/${t.id}`,record:`#${t.ticket_number}`,subject:t.subject||"Support ticket",customer:customerName(t),state:t.status==="staff_reply"?"Needs staff reply":!t.assigned_to?"Unassigned":pretty(t.priority),amount:null,when:t.updated_at,urgent:t.priority==="urgent"||t.status==="staff_reply"}));
  waitingOrders.forEach(o=>items.push({key:`order-${o.id}`,kind:"order",rank:4,href:`/admin/orders/${o.id}`,record:`#${o.order_number||o.id}`,subject:o.status==="pending_payment"?"Payment pending":o.status==="pending_approval"?"Approval required":"Fulfilment waiting",customer:customerName(o),state:pretty(o.status||o.fulfillment_status),amount:Number(o.total_cents||0),when:o.created_at,urgent:false}));
  if(pendingCancellations>0)items.push({key:"cancellations",kind:"cancel",rank:5,href:"/admin/customers/cancellations",record:`${pendingCancellations} request${pendingCancellations===1?"":"s"}`,subject:"Cancellation review",customer:"Customer requests",state:"Admin decision",amount:null,when:null,urgent:false});
  return items.sort((a,b)=>a.rank-b.rank||+(new Date(a.when||0))-(+(new Date(b.when||0)))).slice(0,12);
 },[unpaidInvoices,activeTickets,waitingOrders,pendingCancellations,users]);

 const compactView=<main className="adminShell adminDashboard"><header className="adminTop"><div><p className="eyebrow">OPERATIONS</p><h1>OrbitFS Admin</h1><p className="muted">Priority work, money waiting, customer issues and anything needing action.</p></div></header>
 {pendingCancellations>0&&<Link className="cancellationAlertBanner" href="/admin/customers/cancellations"><div><b>{pendingCancellations} cancellation request{pendingCancellations===1?"":"s"} waiting</b><span>Customer cancellation requests need an admin decision.</span></div><strong>Review →</strong></Link>}
 <section className="dashboardPulse">{can("invoices.view")&&<Link href="/admin/invoices" className="pulseItem priority"><small>Needs attention</small><strong>{attentionTotal}</strong><span>Across billing, support and orders</span></Link>}{can("invoices.view")&&<Link href="/admin/invoices" className="pulseItem money"><small>Unpaid invoices</small><strong>{unpaidInvoices.length}</strong><span>${(outstanding/100).toFixed(2)} outstanding · {overdue.length} overdue</span></Link>}{can("support.manage")&&<Link href="/admin/support" className="pulseItem support"><small>Open support</small><strong>{activeTickets.length}</strong><span>{newTickets.length} new · {staffReply.length} need reply</span></Link>}{can("orders.view")&&<Link href="/admin/orders" className="pulseItem orders"><small>Orders waiting</small><strong>{waitingOrders.length}</strong><span>Payment, approval or fulfilment</span></Link>}{can("customers.cancellations")&&<Link href="/admin/customers/cancellations" className="pulseItem cancel"><small>Cancellations</small><strong>{pendingCancellations}</strong><span>{Number(cancellations.scheduled_count||0)} scheduled</span></Link>}</section>
 <section className="dashboardActionGrid">{can("invoices.view")&&<section className="panel actionSection invoiceAttention"><div className="panelTitle"><div><h2>Unpaid invoices</h2><p className="muted">Money currently outstanding, overdue first.</p></div><Link href="/admin/invoices">All invoices →</Link></div>{unpaidInvoices.slice().sort((a,b)=>(a.due_at?+new Date(a.due_at):Infinity)-(b.due_at?+new Date(b.due_at):Infinity)).slice(0,7).map(i=><Link className={`attentionRow ${i.due_at&&new Date(i.due_at).getTime()<Date.now()?"overdue":""}`} href={`/admin/invoices/${i.id}`} key={i.id}><div><b>{i.invoice_number}</b><span>{pretty(i.status)} · due {i.due_at?new Date(i.due_at).toLocaleDateString():"not set"}</span></div><strong>${(invoiceDue(i)/100).toFixed(2)}</strong></Link>)}{!unpaidInvoices.length&&<div className="compactEmpty">No unpaid invoices.</div>}</section>}
 {can("support.manage")&&<section className="panel actionSection dashboardSupport"><div className="panelTitle"><div><h2>Support queue</h2><p className="muted">Tickets waiting on staff or currently active.</p></div><Link href="/admin/support">Full queue →</Link></div><div className="supportMiniStrip"><span><b>{newTickets.length}</b> new</span><span><b>{staffReply.length}</b> reply</span><span><b>{customerReply.length}</b> customer</span><span><b>{mine.length}</b> mine</span></div>{queue.map(t=><Link className={`supportDashRow ${t.status==="staff_reply"||(!t.assigned_to&&t.status==="open")?"attention":""}`} href={`/admin/support/${t.id}`} key={t.id}><div><div className="ticketTitle"><b>#{t.ticket_number} {t.subject}</b>{!t.assigned_to&&t.status==="open"&&<span className="statusBadge new">NEW</span>}</div><span>{t.support_departments?.name||"No department"} · {pretty(t.status)} · {pretty(t.priority)}</span></div><div><b>{owner(t.assigned_to)}</b><span>{new Date(t.updated_at).toLocaleString()} →</span></div></Link>)}{!queue.length&&<div className="compactEmpty">No active support tickets.</div>}</section>}</section>
 <section className="panel dashboardCustomers"><div className="panelTitle"><div><h2>Recent customers</h2><p className="muted">Latest customer activity for quick access.</p></div><Link href="/admin/customers">View all →</Link></div><div className="customerCompactGrid">{users.slice(0,8).map(u=>{const b=balances.find(x=>x.user_id===u.id);return <Link className="adminItem" href={`/admin/customers/${u.id}`} key={u.id}><div><b>{u.display_name||u.id}</b><span>{u.company_name||"Personal"} · {u.status}</span></div><span>${((b?.available_cents||0)/100).toFixed(2)} →</span></Link>})}</div></section></main>;

 const v3View=<main className="adminShell v3Dashboard">
  <header className="adminTop"><div><p className="eyebrow">OPERATIONS</p><h1>Dashboard</h1><p className="muted">Money waiting, customer issues and work requiring an admin decision.</p></div><div className="v3QuickActions">{can("invoices.view")&&<Link className="buttonlink" href="/admin/billing/create?mode=invoice_only">+ Invoice</Link>}{can("orders.view")&&<Link className="buttonlink secondary" href="/admin/billing/create?mode=order_only">+ Order</Link>}{can("support.ticket_create")&&<Link className="buttonlink secondary" href="/admin/support/new">+ Ticket</Link>}</div><details className="v3MobileCreate"><summary>+ Create</summary><div>{can("invoices.view")&&<Link href="/admin/billing/create?mode=invoice_only">Invoice</Link>}{can("orders.view")&&<Link href="/admin/billing/create?mode=order_only">Order</Link>}{can("support.ticket_create")&&<Link href="/admin/support/new">Ticket</Link>}</div></details></header>
  <section className="v3MetricStrip">{can("invoices.view")&&<Link className="v3Metric urgent" href="#attention"><small>Needs attention</small><strong>{attentionTotal}</strong><span>Billing, support, orders & cancellations</span></Link>}{can("invoices.view")&&<Link className="v3Metric money" href="/admin/invoices"><small>Unpaid invoices</small><strong>${(outstanding/100).toFixed(2)}</strong><span>{unpaidInvoices.length} open · {overdue.length} overdue</span></Link>}{can("support.manage")&&<Link className="v3Metric support" href="/admin/support"><small>Support waiting</small><strong>{newTickets.length+staffReply.length}</strong><span>{newTickets.length} unassigned · {staffReply.length} need reply</span></Link>}{can("orders.view")&&<Link className="v3Metric good" href="/admin/orders"><small>Orders waiting</small><strong>{waitingOrders.length}</strong><span>Payment, approval or fulfilment</span></Link>}{can("customers.cancellations")&&<Link className="v3Metric" href="/admin/customers/cancellations"><small>Cancellations</small><strong>{pendingCancellations}</strong><span>{Number(cancellations.scheduled_count||0)} scheduled</span></Link>}</section>
  <section className="v3Section" id="attention"><div className="v3SectionHead"><div><h2>Needs attention</h2><p>One operational queue across the existing billing, support and order systems.</p></div></div><div className="v3TableHead"><span>Type</span><span>Record</span><span>Customer</span><span>Situation</span><span>Value</span><span>Waiting</span></div>{attentionItems.map(item=><Link className="v3AttentionRow" href={item.href} key={item.key}><span><span className={`v3Type ${item.kind}`}>{item.kind}</span></span><span><b>{item.record}</b><small>{item.subject}</small></span><span className="v3AttentionCustomer">{item.customer}</span><span className={"v3AttentionState "+(item.urgent?"v3StateUrgent":"")}>{item.state}</span><span className="v3Amount">{item.amount==null?"—":`${(item.amount/100).toFixed(2)}`}</span><span className="v3Age">{ageLabel(item.when)}</span></Link>)}{!attentionItems.length&&<div className="v3Empty">Nothing currently needs attention.</div>}</section>
  <section className="v3DashboardColumns">
   {can("invoices.view")&&<div className="v3Stream"><div className="v3SectionHead"><div><h2>Receivables</h2><p>Outstanding invoices, overdue items first.</p></div><Link href="/admin/invoices">All invoices →</Link></div>{unpaidInvoices.slice().sort((a,b)=>(a.due_at?+new Date(a.due_at):Infinity)-(b.due_at?+new Date(b.due_at):Infinity)).slice(0,7).map(i=>{const isOverdue=i.due_at&&new Date(i.due_at).getTime()<Date.now();return <Link className="v3StreamRow" href={`/admin/invoices/${i.id}`} key={i.id}><span><b>{i.invoice_number}</b><small>{customerName(i)} · {isOverdue?"OVERDUE":i.due_at?`Due ${new Date(i.due_at).toLocaleDateString()}`:"No due date"}</small></span><strong>${(invoiceDue(i)/100).toFixed(2)}</strong></Link>})}{!unpaidInvoices.length&&<div className="v3Empty">No unpaid invoices.</div>}</div>}
   {can("support.manage")&&<div className="v3Stream"><div className="v3SectionHead"><div><h2>Support waiting</h2><p>Active tickets ordered by staff attention.</p></div><Link href="/admin/support">Open queue →</Link></div>{queue.map(t=><Link className="v3StreamRow" href={`/admin/support/${t.id}`} key={t.id}><span><b>#{t.ticket_number} {t.subject}</b><small>{t.support_departments?.name||"No department"} · {pretty(t.status)} · {owner(t.assigned_to)}</small></span><strong>{ageLabel(t.updated_at)}</strong></Link>)}{!queue.length&&<div className="v3Empty">No active support tickets.</div>}</div>}
  </section>
  {can("customers.view")&&<section className="v3Stream"><div className="v3SectionHead"><div><h2>Recent customers</h2><p>Latest customer records for quick access.</p></div><Link href="/admin/customers">All customers →</Link></div>{users.slice(0,6).map(u=>{const b=balances.find(x=>x.user_id===u.id);return <Link className="v3StreamRow" href={`/admin/customers/${u.id}`} key={u.id}><span><b>{u.display_name||u.id}</b><small>{u.company_name||"Personal"} · {pretty(u.status)}</small></span><strong>${((b?.available_cents||0)/100).toFixed(2)} credit</strong></Link>})}</section>}
 </main>;

 return <><div className="dashboardCompactView">{compactView}</div><div className="dashboardV3View">{v3View}</div></>;
}
