"use client";
import {use,useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase";
import {usePermissions} from "@/lib/usePermissions";
import InvoiceAdminTabs from "@/components/InvoiceAdminTabs";

const states=[["unpaid","Unpaid / Pending Payment"],["overdue","Overdue / Pending Payment"],["paid","Paid / Active"],["apaid","APAID / Active"],["refunded","Refunded / Closed"],["suspended","Suspended / Suspended"],["cancelled","Canceled / Terminated"]];
const standaloneStates=[["unpaid","Unpaid / Pending Payment"],["overdue","Overdue / Pending Payment"],["paid","Paid / Closed"],["apaid","APAID / Paid"],["refunded","Refunded / Closed"],["cancelled","Canceled / Closed"]];
const money=(n:any,c="AUD")=>new Intl.NumberFormat("en-AU",{style:"currency",currency:c}).format(Number(n||0)/100);
const REQUEST_TIMEOUT_MS=10000;

async function boundedFetch(input:RequestInfo|URL,init:RequestInit={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(input,{...init,signal:init.signal||controller.signal,cache:"no-store"})}catch(e:any){if(e?.name==="AbortError")throw new Error(`Request timed out after ${REQUEST_TIMEOUT_MS}ms`);throw e}finally{clearTimeout(timer)}}

export default function InvoiceDetail({params}:{params:Promise<{id:string}>}){
 const {id}=use(params),sb=createClient(),{can}=usePermissions();
 const [inv,setInv]=useState<any>(),[items,setItems]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[customer,setCustomer]=useState<any>(),[balance,setBalance]=useState<any>(),[audit,setAudit]=useState<any[]>([]);
 const [state,setState]=useState("unpaid"),[form,setForm]=useState<any>({}),[msg,setMsg]=useState("");
 function derive(i:any,o:any){if(i?.status==="refunded")return"refunded";if(o?.status==="terminated"||["cancelled","void"].includes(i?.status))return"cancelled";if(o?.status==="suspended")return"suspended";if(o?.payment_status==="paid_admin_override")return"apaid";if(o?.payment_status?.startsWith("paid")||i?.status==="paid")return"paid";if(i?.status==="overdue"||o?.payment_status==="overdue")return"overdue";return"unpaid"}
 async function load(){
  const {data:i}=await sb.from("invoices").select("*").eq("id",id).single();
  if(!i)return;
  const orderRequest=i.order_id?sb.from("orders").select("*").eq("id",i.order_id).single():Promise.resolve({data:null,error:null});
  const [it,py,or,cu,cr,ba,au]=await Promise.all([
   sb.from("invoice_items").select("*").eq("invoice_id",id).limit(50),
   sb.from("invoice_payments").select("*").eq("invoice_id",id).order("created_at",{ascending:false}).limit(20),
   orderRequest,
   sb.from("user_profiles").select("*").eq("id",i.auth_user_id).single(),
   sb.from("customers").select("*").eq("auth_user_id",i.auth_user_id).maybeSingle(),
   sb.from("account_balances").select("*").eq("user_id",i.auth_user_id).maybeSingle(),
   sb.from("admin_audit_log").select("*").eq("target_id",id).order("created_at",{ascending:false}).limit(12)
  ]);
  setInv(i);setItems(it.data||[]);setPayments(py.data||[]);setCustomer({...((cr.data)||{}),...((cu.data)||{}),email:cr.data?.email||null,customer_record_id:cr.data?.id||null});setBalance(ba.data);setAudit(au.data||[]);setState(derive(i,or.data));setForm({due_at:i.due_at?String(i.due_at).slice(0,16):"",notes:i.notes||"",subtotal:(i.subtotal_cents/100).toFixed(2),discount:(Number(i.discount_cents||0)/100).toFixed(2),tax:(Number(i.tax_cents||0)/100).toFixed(2),total:(i.total_cents/100).toFixed(2)})
 }
 useEffect(()=>{load()},[id]);
 async function save(){const reason=prompt("Reason for editing this invoice?")||null;const {error}=await sb.rpc("admin_edit_invoice",{p_invoice_id:id,p_due_at:form.due_at?new Date(form.due_at).toISOString():null,p_notes:form.notes||null,p_subtotal_cents:Math.round(Number(form.subtotal||0)*100),p_discount_cents:Math.round(Number(form.discount||0)*100),p_tax_cents:Math.round(Number(form.tax||0)*100),p_total_cents:Math.round(Number(form.total||0)*100),p_reason:reason});setMsg(error?.message||"Invoice saved.");if(!error)load()}
 async function notifyState(next:string,reason:string){const eventKeys:Record<string,string>=inv?.order_id?{paid:"invoice.paid",overdue:"invoice.overdue",suspended:"service.suspended",cancelled:"service.terminated"}:{paid:"invoice.paid",overdue:"invoice.overdue"};const key=eventKeys[next];if(!key||!customer?.email)return;const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)return;await boundedFetch("/api/mail/transactional",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({eventKey:key,to:customer.email,vars:{customer_name:customer?.display_name||customer?.name||"Customer",invoice_number:inv.invoice_number||"",invoice_due:money(Math.max(0,Number(inv.total_cents)-Number(inv.paid_cents||0)),inv.currency||"AUD"),order_number:"",reason:reason||""},relatedType:key.startsWith("invoice.")?"invoice":"order",relatedId:key.startsWith("invoice.")?id:inv.order_id})}).catch(()=>null)}
 async function fulfilPaidOrder(orderId:string){const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)throw new Error("Staff session expired; sign in again");const response=await boundedFetch("/api/admin/license-master/fulfill",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({orderId})});const data=await response.json().catch(()=>({}));if(!response.ok||data?.ok===false)throw new Error(data?.error||`License fulfilment failed (${response.status})`);return data}
 async function applyState(){if(state==="refunded")return setMsg("Refunded status is managed automatically from successful refund records.");const reason=prompt("Reason for changing billing state?");if(reason===null)return;const {error}=await sb.rpc("admin_set_invoice_billing_state",{p_invoice_id:id,p_state:state,p_reason:reason||null});if(error){setMsg(error.message||"Billing state update failed.");return}let fulfilmentMsg="";if(inv?.order_id&&(state==="paid"||state==="apaid")){try{const result=await fulfilPaidOrder(inv.order_id);fulfilmentMsg=result.failed?` Billing marked ${state}; ${result.fulfilled} licence item(s) fulfilled and ${result.failed} failed.`:` Billing marked ${state}; ${result.fulfilled} licence item(s) fulfilled through License Master.`}catch(e:any){fulfilmentMsg=` Billing marked ${state}, but License Master fulfilment is pending: ${e?.message||"connection failed"}.`}}await notifyState(state,reason||"");setMsg(`Billing state updated.${fulfilmentMsg}`);load()}
 async function editItem(x:any){const desc=prompt("Line description",x.description);if(desc===null)return;const qty=prompt("Quantity",String(x.quantity));if(qty===null)return;const price=prompt("Unit price in dollars",(Number(x.unit_price_cents)/100).toFixed(2));if(price===null)return;const reason=prompt("Reason for editing this line?")||null;const {error}=await sb.rpc("admin_edit_invoice_item",{p_item_id:x.id,p_description:desc,p_quantity:Number(qty),p_unit_price_cents:Math.round(Number(price)*100),p_reason:reason});setMsg(error?.message||"Invoice line updated.");if(!error)load()}
 if(!inv)return <main className="adminShell">Loading invoice…</main>;
 const closed=["refunded","cancelled","void"].includes(String(inv.status||"").toLowerCase()),due=closed?0:Math.max(0,Number(inv.total_cents)-Number(inv.paid_cents||0)),currency=inv.currency||"AUD",name=customer?.display_name||[customer?.first_name,customer?.last_name].filter(Boolean).join(" ")||"Customer",statusOptions=inv.order_id?states:standaloneStates;
 return <main className="adminShell invoiceAdminPage compactInvoiceAdmin"><header className="adminTop invoiceAdminHeader"><div><p className="eyebrow">INVOICE</p><div className="invoiceTitleRow"><h1>{inv.invoice_number}</h1><span className={`invoiceStatusPill status-${inv.status}`}>{String(inv.status).replaceAll("_"," ")}</span></div><p className="muted">{name} · created {new Date(inv.created_at).toLocaleString()}{!inv.order_id?" · standalone invoice":""}</p></div><div className="inlineActions invoiceHeaderActions"><Link className="buttonlink secondary" href={`/admin/invoices/${id}/payments`}>Payments</Link><Link className="buttonlink secondary" href={`/admin/invoices/${id}/notes`}>Notes</Link><Link className="buttonlink secondary" href={`/admin/customers/${inv.auth_user_id}`}>Customer</Link>{inv.order_id&&<Link className="buttonlink secondary" href={`/admin/orders/${inv.order_id}`}>Order</Link>}</div></header>
 <InvoiceAdminTabs invoiceId={id}/>
 <section className="invoiceSummaryGrid slim"><article><small>Total</small><strong>{money(inv.total_cents,currency)}</strong></article><article><small>Paid</small><strong>{money(inv.paid_cents,currency)}</strong></article><article><small>Due</small><strong>{money(due,currency)}</strong></article><article><small>Due date</small><strong>{inv.due_at?new Date(inv.due_at).toLocaleDateString():"—"}</strong></article></section>
 <section className="panel invoiceCustomerPrimary"><div className="sectionHead"><div><h2>Customer & billing</h2><p className="muted">Primary client and billing context for this invoice.</p></div><Link className="buttonlink secondary small" href={`/admin/customers/${inv.auth_user_id}`}>Open customer</Link></div><div className="customerPrimaryGrid"><div><b>{name}</b><span>{customer?.company_name||"Personal account"}</span><span>{customer?.phone||"No phone"}</span></div><div><small>Billing address</small><span>{[customer?.address_line1,customer?.address_line2,customer?.city,customer?.state_region,customer?.postal_code,customer?.country_code].filter(Boolean).join(", ")||"No billing address saved"}</span></div><div><small>Account credit</small><strong>{money(balance?.available_cents||0,currency)}</strong></div><div><small>Currency</small><strong>{currency}</strong></div></div></section>
 <section className="panel invoiceStatusBar"><div><small>Invoice status</small><strong>{String(inv.status).replaceAll("_"," ")}</strong><span>{inv.status==="refunded"?"Refunded and closed":due>0?`${money(due,currency)} outstanding`:"No balance due"}</span></div><div className="invoiceStatusControl"><select value={state} onChange={e=>setState(e.target.value)}>{statusOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{(can("invoices.edit")||can("orders.edit"))&&state!=="refunded"&&<button onClick={applyState}>Update status</button>}</div></section>
 <div className="invoiceOverviewGrid streamlined"><div className="invoiceMainColumn">
 <section className="panel invoiceDetailsCompact"><div className="sectionHead"><div><h2>Invoice details</h2><p className="muted">Dates, totals and internal information.</p></div></div><div className="form invoiceDetailsForm"><div className="two"><label>Due date<input type="datetime-local" value={form.due_at||""} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label>Internal note<textarea rows={2} value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Internal invoice note"/></label></div><div className="invoiceMoneyEdit"><label>Subtotal<input type="number" step="0.01" value={form.subtotal||""} onChange={e=>setForm({...form,subtotal:e.target.value})}/></label><label>Discount<input type="number" step="0.01" value={form.discount||""} onChange={e=>setForm({...form,discount:e.target.value})}/></label><label>Tax<input type="number" step="0.01" value={form.tax||""} onChange={e=>setForm({...form,tax:e.target.value})}/></label><label>Total<input type="number" step="0.01" value={form.total||""} onChange={e=>setForm({...form,total:e.target.value})}/></label></div>{can("invoices.edit")&&<button className="invoiceSaveButton" onClick={save}>Save invoice details</button>}</div></section>
 <section className="panel"><div className="sectionHead"><div><h2>Invoice lines</h2><p className="muted">Products and charges on this invoice.</p></div><span>{items.length} line{items.length===1?"":"s"}</span></div><div className="invoiceLineTable"><div className="invoiceLineHead"><span>Description</span><span>Qty</span><span>Unit</span><span>Total</span><span></span></div>{items.map(x=><div className="invoiceLineRow" key={x.id}><div><b>{x.description}</b></div><span>{x.quantity}</span><span>{money(x.unit_price_cents,currency)}</span><strong>{money(x.total_cents,currency)}</strong>{can("invoices.edit_items")?<button className="small secondary" onClick={()=>editItem(x)}>Edit</button>:<span/>}</div>)}</div></section>
 </div><aside className="invoiceSideColumn">
 <section className="panel"><div className="sectionHead"><div><h2>Recent activity</h2><p className="muted">Latest billing changes and payments.</p></div></div><div className="invoiceActivity">{payments.slice(0,3).map(p=><div className="activityRow" key={`p-${p.id}`}><div><b>Payment received</b><span>{String(p.method||"payment").replaceAll("_"," ")}</span></div><div><strong>{money(p.amount_cents,currency)}</strong><span>{new Date(p.created_at).toLocaleString()}</span></div></div>)}{audit.slice(0,4).map(a=><div className="activityRow" key={a.id}><div><b>{String(a.action||"update").replaceAll("_"," ")}</b><span>{a.actor_email||"Staff action"}</span></div><span>{new Date(a.created_at).toLocaleString()}</span></div>)}{!payments.length&&!audit.length&&<p className="muted">No activity recorded yet.</p>}</div></section>
 <section className="panel invoiceQuickLinks"><h2>Invoice tools</h2><Link href={`/admin/invoices/${id}/payments`}><span>Payments & history</span><b>→</b></Link><Link href={`/admin/invoices/${id}/notes`}><span>Invoice notes</span><b>→</b></Link><Link href={`/portal/invoices/${id}`} target="_blank"><span>Preview customer invoice</span><b>↗</b></Link><Link href="/admin/settings/invoices"><span>Invoice settings</span><b>→</b></Link></section>
 </aside></div>{msg&&<p className="inlineStatus">{msg}</p>}</main>;
}
