"use client";
import {useEffect,useRef,useState} from "react";
import {PREMADE_SUPPORT_VARIABLES} from "@/lib/support-premade-variables";
import {createClient} from "@/lib/supabase";
import {usePermissions} from "@/lib/usePermissions";
export default function PremadeMessages(){const sb=createClient(),{can}=usePermissions();const [rows,setRows]=useState<any[]>([]),[edit,setEdit]=useState<any>({active:true,category:'General',sort_order:0}),[msg,setMsg]=useState(''),bodyRef=useRef<HTMLTextAreaElement>(null);
function insertVariable(key:string){
 const token=`{${key}}`;
 const input=bodyRef.current;
 const current=String(edit.body||'');
 const start=input?.selectionStart??current.length;
 const end=input?.selectionEnd??start;
 setEdit((previous:any)=>({...previous,body:current.slice(0,start)+token+current.slice(end)}));
 requestAnimationFrame(()=>{
  bodyRef.current?.focus();
  bodyRef.current?.setSelectionRange(start+token.length,start+token.length);
 });
}
async function load(){const {data}=await sb.from('support_premade_messages').select('*').order('category').order('sort_order');setRows(data||[])}useEffect(()=>{load()},[]);
async function save(){if(!edit.name?.trim()||!edit.body?.trim())return setMsg('Name and message are required.');const payload={name:edit.name.trim(),category:edit.category||'General',body:edit.body,active:!!edit.active,sort_order:Number(edit.sort_order||0),updated_at:new Date().toISOString()};const q=edit.id?sb.from('support_premade_messages').update(payload).eq('id',edit.id):sb.from('support_premade_messages').insert(payload);const {error}=await q;setMsg(error?.message||'Premade message saved.');if(!error){setEdit({active:true,category:'General',sort_order:0});load()}}
async function remove(id:string){if(!confirm('Delete this premade message?'))return;const {error}=await sb.from('support_premade_messages').delete().eq('id',id);setMsg(error?.message||'Premade message deleted.');if(!error)load()}
return <main className="adminShell settingsPage"><header className="adminTop"><div><p className="eyebrow">SUPPORT CONTENT</p><h1>Premade Messages</h1><p className="muted">Reusable support replies shown as quick buttons inside ticket conversations. These are separate from automatic lifecycle messages.</p></div></header><div className="adminGrid"><section className="panel"><div className="panelTitle"><div><h2>Message library</h2><p className="muted">Support staff can insert an enabled message into a reply, then edit it before sending.</p></div>{can('support.premade.manage')&&<button onClick={()=>setEdit({active:true,category:'General',sort_order:0})}>New message</button>}</div>{rows.map(x=><div className="adminItem" key={x.id}><button className="plainButton" onClick={()=>setEdit({...x})}><b>{x.name}</b><span>{x.category} · {x.active?'Enabled':'Disabled'}</span><small>{x.body.slice(0,110)}{x.body.length>110?'…':''}</small></button>{can('support.premade.manage')&&<button className="small danger" onClick={()=>remove(x.id)}>Delete</button>}</div>)}</section>{can('support.premade.manage')&&<section className="panel"><h2>{edit.id?'Edit premade message':'New premade message'}</h2><div className="form"><label>Name<input value={edit.name||''} onChange={e=>setEdit({...edit,name:e.target.value})} placeholder="e.g. Request diagnostic logs"/></label><label>Category<input value={edit.category||''} onChange={e=>setEdit({...edit,category:e.target.value})} placeholder="General, Billing, Licensing…"/></label><label>Message<textarea ref={bodyRef} rows={9} value={edit.body||''} onChange={e=>setEdit({...edit,body:e.target.value})} placeholder="Message inserted into the reply composer…"/></label><details className="panel" style={{padding:12}} open><summary style={{cursor:'pointer',fontWeight:650}}>Available message variables</summary><p className="muted">Click to insert at your cursor. These are filled from the ticket when staff select a premade reply. If an optional value is unavailable, its placeholder stays visible so it can be edited before sending.</p><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{PREMADE_SUPPORT_VARIABLES.map(variable=><button key={variable.key} type="button" className="small secondary" onClick={()=>insertVariable(variable.key)} title={variable.description}><code>{'{' + variable.key + '}'}</code> — {variable.label}</button>)}</div></details><label>Sort order<input type="number" value={edit.sort_order||0} onChange={e=>setEdit({...edit,sort_order:e.target.value})}/></label><label className="toggle"><input type="checkbox" checked={!!edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/>Enabled for support staff</label><div className="inlineActions"><button onClick={save}>{edit.id?'Save changes':'Create message'}</button>{edit.id&&<button className="secondary" onClick={()=>setEdit({active:true,category:'General',sort_order:0})}>Cancel</button>}</div></div></section>}</div><p>{msg}</p></main>}
