"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase";
import {NEWS_CATEGORIES,newsCategoryLabel,newsPublishState,newsPublishStateLabel,slugifyNews} from "@/lib/news";
import styles from "./news-admin.module.css";

type Mode="draft"|"publish"|"schedule";
const blank=()=>({category:"product_updates",published:false,pinned:false,featured:false,show_on_homepage:true,author_name:"OrbitFS",title:"",slug:"",excerpt:"",body:"",cta_label:"",cta_url:"",seo_title:"",seo_description:"",unpublish_at:null,published_at:null});
function localValue(value?:string|null){if(!value)return "";const d=new Date(value);if(Number.isNaN(d.getTime()))return "";const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,16)}
function isoValue(value:string){return value?new Date(value).toISOString():null}

export default function NewsAdmin(){
  const sb=createClient();
  const [rows,setRows]=useState<any[]>([]),[edit,setEdit]=useState<any>(blank()),[mode,setMode]=useState<Mode>("draft"),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[msg,setMsg]=useState(""),[preview,setPreview]=useState(false),[saving,setSaving]=useState(false);

  async function load(){const {data,error}=await sb.from("news_posts").select("*").order("created_at",{ascending:false});if(error)setMsg(error.message);setRows(data||[])}
  useEffect(()=>{load()},[]);
  function select(post:any){setEdit({...post});const state=newsPublishState(post);setMode(state==="scheduled"?"schedule":state==="published"?"publish":"draft");setMsg("");setPreview(false)}
  function fresh(){setEdit(blank());setMode("draft");setMsg("");setPreview(false)}
  function changeTitle(title:string){const oldAuto=slugifyNews(edit.title||"");setEdit({...edit,title,slug:(!edit.slug||edit.slug===oldAuto)?slugifyNews(title):edit.slug})}
  function changeCategory(category:string){setEdit({...edit,category,show_on_homepage:category==="product_updates"?(edit.category==="product_updates"?!!edit.show_on_homepage:true):false})}
  function addFormat(kind:"h2"|"h3"|"bullet"|"quote"){const sample=kind==="h2"?"## Section heading":kind==="h3"?"### Subheading":kind==="bullet"?"- List item":"> Highlighted note";setEdit({...edit,body:`${edit.body||""}${edit.body?"\n\n":""}${sample}`})}

  async function save(e?:FormEvent){e?.preventDefault();setMsg("");if(!edit.title?.trim()){setMsg("A title is required.");return}const slug=slugifyNews(edit.slug||edit.title);if(!slug){setMsg("A valid slug is required.");return}if(mode==="schedule"&&!edit.published_at){setMsg("Choose a scheduled publish date and time.");return}if(mode==="schedule"&&new Date(edit.published_at).getTime()<=Date.now()){setMsg("Scheduled publishing must be in the future.");return}setSaving(true);
    const payload={slug,title:edit.title.trim(),excerpt:edit.excerpt?.trim()||null,body:edit.body?.trim()||null,category:edit.category||"general_news",published:mode!=="draft",pinned:!!edit.pinned,featured:!!edit.featured,show_on_homepage:edit.category==="product_updates"&&!!edit.show_on_homepage,published_at:mode==="draft"?null:mode==="publish"?new Date().toISOString():isoValue(edit.published_at),unpublish_at:isoValue(edit.unpublish_at||""),author_name:edit.author_name?.trim()||null,cta_label:edit.cta_label?.trim()||null,cta_url:edit.cta_url?.trim()||null,seo_title:edit.seo_title?.trim()||null,seo_description:edit.seo_description?.trim()||null,updated_at:new Date().toISOString()};
    const q=edit.id?sb.from("news_posts").update(payload).eq("id",edit.id).select().single():sb.from("news_posts").insert(payload).select().single();const {data,error}=await q;setSaving(false);if(error){setMsg(error.message);return}setMsg(mode==="draft"?"Draft saved.":mode==="schedule"?"Post scheduled.":"Post published.");if(data)select(data);await load()
  }
  async function remove(){if(!edit.id||!confirm(`Delete “${edit.title}”? This cannot be undone.`))return;const {error}=await sb.from("news_posts").delete().eq("id",edit.id);if(error){setMsg(error.message);return}fresh();setMsg("Post deleted.");await load()}
  function duplicate(){const title=`${edit.title||"Untitled"} copy`;setEdit({...edit,id:undefined,title,slug:slugifyNews(title),published:false,published_at:null,unpublish_at:null,pinned:false,featured:false,created_at:undefined,updated_at:undefined});setMode("draft");setMsg("Duplicated into a new draft. Save when ready.")}

  const visible=useMemo(()=>rows.filter(r=>{const state=newsPublishState(r);const matchesFilter=filter==="all"||filter===state||filter===r.category;const q=search.trim().toLowerCase();return matchesFilter&&(!q||`${r.title} ${r.slug} ${newsCategoryLabel(r.category)}`.toLowerCase().includes(q))}),[rows,search,filter]);
  const stats=useMemo(()=>({total:rows.length,published:rows.filter(x=>newsPublishState(x)==="published").length,draft:rows.filter(x=>newsPublishState(x)==="draft").length,scheduled:rows.filter(x=>newsPublishState(x)==="scheduled").length}),[rows]);

  return <main className={styles.page}>
    <header className={styles.top}><div><p className={styles.eyebrow}>Content management</p><h1>News Studio</h1><p>Create, schedule and manage everything published through OrbitFS News.</p></div><div className={styles.topActions}><Link className={styles.button} href="/news" target="_blank">Open public news ↗</Link><button className={styles.buttonPrimary} onClick={fresh}>+ New post</button></div></header>

    <div className={styles.stats}><div className={styles.stat}><span>Total posts</span><b>{stats.total}</b></div><div className={styles.stat}><span>Published</span><b>{stats.published}</b></div><div className={styles.stat}><span>Drafts</span><b>{stats.draft}</b></div><div className={styles.stat}><span>Scheduled</span><b>{stats.scheduled}</b></div></div>

    <div className={styles.layout}>
      <aside className={styles.library}><div className={styles.libraryHead}><div className={styles.libraryHeadRow}><h2>Post library</h2><button className={styles.iconButton} onClick={fresh}>+</button></div><input className={styles.search} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search news…"/><div className={styles.tabs}><button className={`${styles.tab} ${filter==="all"?styles.tabActive:""}`} onClick={()=>setFilter("all")}>All</button><button className={`${styles.tab} ${filter==="published"?styles.tabActive:""}`} onClick={()=>setFilter("published")}>Published</button><button className={`${styles.tab} ${filter==="draft"?styles.tabActive:""}`} onClick={()=>setFilter("draft")}>Drafts</button><button className={`${styles.tab} ${filter==="scheduled"?styles.tabActive:""}`} onClick={()=>setFilter("scheduled")}>Scheduled</button>{NEWS_CATEGORIES.map(c=><button key={c.value} className={`${styles.tab} ${filter===c.value?styles.tabActive:""}`} onClick={()=>setFilter(c.value)}>{c.shortLabel}</button>)}</div></div><div className={styles.posts}>{visible.length?visible.map(n=>{const state=newsPublishState(n);return <button className={`${styles.post} ${edit.id===n.id?styles.postActive:""}`} key={n.id} onClick={()=>select(n)}><div className={styles.postTop}><span className={styles.postTitle}>{n.title}</span><span className={`${styles.postState} ${state==="published"?styles.postStatePublished:state==="scheduled"?styles.postStateScheduled:state==="expired"?styles.postStateExpired:styles.postStateDraft}`}>{newsPublishStateLabel(n)}</span></div><div className={styles.postMeta}>{newsCategoryLabel(n.category)}{n.pinned?" · Pinned":""}{n.featured?" · Featured":""}</div></button>}):<div className={styles.emptyLibrary}>No posts match this view.</div>}</div></aside>

      <section className={styles.editor}><div className={styles.editorTop}><div><h2>{edit.id?"Edit news post":"Create news post"}</h2><p>{edit.id?`Last updated ${edit.updated_at?new Date(edit.updated_at).toLocaleString("en-AU"):"recently"}`:"Build the article, then choose how and when it publishes."}</p></div><span className={styles.saveState}>{msg}</span></div>
        <form className={styles.form} onSubmit={save}>
          <section className={styles.section}><div className={styles.sectionHead}><h3>Story</h3><span>Title, category and summary</span></div><div className={styles.field}><label>Title</label><input className={styles.titleInput} value={edit.title||""} onChange={e=>changeTitle(e.target.value)} placeholder="What’s new with OrbitFS?"/></div><div className={styles.grid2} style={{marginTop:10}}><div className={styles.field}><label>Category</label><select value={edit.category||"product_updates"} onChange={e=>changeCategory(e.target.value)}>{NEWS_CATEGORIES.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select><span className={styles.hint}>{NEWS_CATEGORIES.find(c=>c.value===edit.category)?.description}</span></div><div className={styles.field}><label>URL slug</label><input value={edit.slug||""} onChange={e=>setEdit({...edit,slug:slugifyNews(e.target.value)})} placeholder="orbitfs-update"/><span className={styles.hint}>/news/{edit.slug||"your-post"}</span></div></div><div className={styles.field} style={{marginTop:10}}><label>Excerpt</label><textarea rows={3} value={edit.excerpt||""} onChange={e=>setEdit({...edit,excerpt:e.target.value})} placeholder="Short summary shown on the homepage and news cards."/></div></section>

          <section className={styles.section}><div className={styles.sectionHead}><h3>Article</h3><span>Simple formatting supported</span></div><div className={styles.toolbar}><button type="button" onClick={()=>addFormat("h2")}>H2 section</button><button type="button" onClick={()=>addFormat("h3")}>H3 heading</button><button type="button" onClick={()=>addFormat("bullet")}>• Bullet</button><button type="button" onClick={()=>addFormat("quote")}>Quote / note</button></div><div className={styles.field}><textarea rows={16} value={edit.body||""} onChange={e=>setEdit({...edit,body:e.target.value})} placeholder={"Write the full article…\n\n## Section heading\n- List item\n> Highlighted note"}/><span className={styles.hint}>Use ## for section headings, ### for subheadings, - for lists and &gt; for highlighted notes.</span></div></section>

          <section className={styles.section}><div className={styles.sectionHead}><h3>Publishing</h3><span>Draft, immediate or scheduled</span></div><div className={styles.publishMode}><button type="button" className={`${styles.mode} ${mode==="draft"?styles.modeActive:""}`} onClick={()=>setMode("draft")}><b>Save as draft</b><span>Hidden from the public site.</span></button><button type="button" className={`${styles.mode} ${mode==="publish"?styles.modeActive:""}`} onClick={()=>setMode("publish")}><b>Publish now</b><span>Make this update public immediately.</span></button><button type="button" className={`${styles.mode} ${mode==="schedule"?styles.modeActive:""}`} onClick={()=>setMode("schedule")}><b>Schedule</b><span>Automatically appears at a future time.</span></button></div>{mode==="schedule"&&<div className={styles.grid2} style={{marginTop:10}}><div className={styles.field}><label>Publish date & time</label><input type="datetime-local" value={localValue(edit.published_at)} onChange={e=>setEdit({...edit,published_at:e.target.value})}/></div><div className={styles.field}><label>Optional unpublish date & time</label><input type="datetime-local" value={localValue(edit.unpublish_at)} onChange={e=>setEdit({...edit,unpublish_at:e.target.value})}/></div></div>}{mode!=="schedule"&&<div className={styles.field} style={{marginTop:10}}><label>Optional automatic unpublish</label><input type="datetime-local" value={localValue(edit.unpublish_at)} onChange={e=>setEdit({...edit,unpublish_at:e.target.value})}/><span className={styles.hint}>Leave blank to keep the post available indefinitely.</span></div>}</section>

          <section className={styles.section}><div className={styles.sectionHead}><h3>Placement & presentation</h3><span>Control where the story is promoted</span></div><div className={styles.toggles}><label className={styles.toggle}><input type="checkbox" checked={!!edit.pinned} onChange={e=>setEdit({...edit,pinned:e.target.checked})}/><span><b>Pin post</b><span>Prioritise it above normal posts.</span></span></label><label className={styles.toggle}><input type="checkbox" checked={!!edit.featured} onChange={e=>setEdit({...edit,featured:e.target.checked})}/><span><b>Feature on News</b><span>Use as the large lead story on /news.</span></span></label><label className={styles.toggle}><input type="checkbox" disabled={edit.category!=="product_updates"} checked={edit.category==="product_updates"&&!!edit.show_on_homepage} onChange={e=>setEdit({...edit,show_on_homepage:e.target.checked})}/><span><b>Homepage update</b><span>Product News and Updates can appear in the homepage section shown in your screenshot.</span></span></label></div><div className={styles.grid3} style={{marginTop:10}}><div className={styles.field}><label>Author / byline</label><input value={edit.author_name||""} onChange={e=>setEdit({...edit,author_name:e.target.value})} placeholder="OrbitFS"/></div><div className={styles.field}><label>CTA label</label><input value={edit.cta_label||""} onChange={e=>setEdit({...edit,cta_label:e.target.value})} placeholder="Explore OrbitFS"/></div><div className={styles.field}><label>CTA URL</label><input value={edit.cta_url||""} onChange={e=>setEdit({...edit,cta_url:e.target.value})} placeholder="/"/></div></div></section>

          <section className={styles.section}><div className={styles.sectionHead}><h3>Search & sharing</h3><span>Optional metadata</span></div><div className={styles.grid2}><div className={styles.field}><label>SEO title</label><input value={edit.seo_title||""} onChange={e=>setEdit({...edit,seo_title:e.target.value})} placeholder={edit.title||"Search title"}/></div><div className={styles.field}><label>SEO description</label><input value={edit.seo_description||""} onChange={e=>setEdit({...edit,seo_description:e.target.value})} placeholder={edit.excerpt||"Short search description"}/></div></div></section>

          <div className={styles.footerActions}><div>{edit.id&&<button type="button" className={styles.buttonDanger} onClick={remove}>Delete</button>}{edit.id&&<button type="button" className={styles.button} onClick={duplicate}>Duplicate</button>}<button type="button" className={styles.button} onClick={()=>setPreview(!preview)}>{preview?"Hide preview":"Preview"}</button></div><div><span className={styles.message}>{msg}</span><button className={styles.buttonPrimary} disabled={saving}>{saving?"Saving…":mode==="draft"?"Save draft":mode==="schedule"?"Schedule post":"Publish post"}</button></div></div>
        </form>

        {preview&&<section className={styles.preview}><span className={styles.previewBadge}>{newsCategoryLabel(edit.category)}</span><h2>{edit.title||"Untitled news post"}</h2><p className={styles.previewLead}>{edit.excerpt||"Your excerpt will appear here."}</p><div className={styles.previewBody}>{edit.body||"Your article content will appear here."}</div></section>}
      </section>
    </div>
  </main>
}
