import {createClient} from "@supabase/supabase-js";
import {orbitFsEmailTemplate,sendEmail} from "@/lib/email";
import {loadMailRuntimeConfig} from "@/lib/mail-config-server";

const url=process.env.NEXT_PUBLIC_SUPABASE_URL||"";
const publicKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"";
const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY!;

async function requireEmailAdmin(req:Request){
 const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)return {error:Response.json({error:"Authentication required."},{status:401})};
 const userDb=createClient(url,publicKey,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const {data:{user},error:userError}=await userDb.auth.getUser(token);if(userError||!user)return {error:Response.json({error:"Invalid session."},{status:401})};
 const {data:access}=await userDb.rpc("get_my_staff_access");const allowed=!!access?.permissions?.all||!!access?.permissions?.["mail.settings"];if(!allowed)return {error:Response.json({error:"Mail settings permission required."},{status:403})};
 const service=serviceKey?createClient(url,serviceKey,{auth:{persistSession:false}}):null;return {user,service,userDb};
}

export async function GET(req:Request){
 const auth:any=await requireEmailAdmin(req);if(auth.error)return auth.error;const config=await loadMailRuntimeConfig(auth.userDb);
 return Response.json({ok:true,provider:"Resend transport",configured:!!process.env.RESEND_API_KEY,mailboxConfigured:!!process.env.RESEND_MAIL_API_KEY,from:`${config.outbound.sender_name} <${config.outbound.default_from}>`,replyTo:config.outbound.reply_to,source:"OrbitFS Mail / Supabase"});
}

export async function POST(req:Request){
 const auth:any=await requireEmailAdmin(req);if(auth.error)return auth.error;const body=await req.json().catch(()=>({}));const to=String(body.to||auth.user?.email||"").trim();if(!to)return Response.json({error:"Recipient email is required."},{status:400});
 try{
  const result=await sendEmail({to,subject:"OrbitFS Mail outbound test",text:"OrbitFS Mail is configured and the outbound transport is working.",html:orbitFsEmailTemplate("OrbitFS Mail is working","<p>This is a live test generated by OrbitFS Mail.</p><p>Sender identity and reply configuration came from OrbitFS Mail settings in Supabase; Resend was used only as the delivery transport.</p>")});
  if(auth.service)await auth.service.from("admin_audit_log").insert({actor_id:auth.user?.id,action:"email.test_sent",target_type:"email",target_id:result.id,detail:{to,provider:"resend",system:"orbitfs_mail"}});
  return Response.json({ok:true,id:result.id,to});
 }catch(error){return Response.json({error:error instanceof Error?error.message:"Email send failed."},{status:500})}
}
