import {canUseMailbox,requireMailUser} from "@/lib/mail-auth";
async function payload(r:Response){const text=await r.text();if(!text)return {};try{return JSON.parse(text)}catch{return {message:text}}}
function addressFrom(input:string){const value=String(input||"").toLowerCase();return value.includes("@")?value:`${value}@orbitfs.cc`}
function resendMailKey(){return String(process.env.RESEND_MAIL_API_KEY||process.env.RESEND_API_KEY||"").trim()}
export async function GET(req:Request,{params}:{params:Promise<{id:string}>}){
 const ctx:any=await requireMailUser(req);if(ctx.error)return ctx.error;const key=resendMailKey();if(!key)return Response.json({error:"Inbound/mailbox transport is not configured. Set RESEND_API_KEY (or RESEND_MAIL_API_KEY for a separate inbound key)."},{status:503});
 const {id}=await params;const u=new URL(req.url),direction=u.searchParams.get("direction")==="outbound"?"outbound":"inbound",address=addressFrom(u.searchParams.get("account")||"admin");if(!await canUseMailbox(ctx,address,false))return Response.json({error:"You do not have access to this mailbox."},{status:403});
 const endpoint=direction==="outbound"?`https://api.resend.com/emails/${encodeURIComponent(id)}`:`https://api.resend.com/emails/receiving/${encodeURIComponent(id)}`;const r=await fetch(endpoint,{headers:{Authorization:`Bearer ${key}`},cache:"no-store"});const j:any=await payload(r);if(!r.ok)return Response.json({error:j?.message||`Mail provider returned ${r.status}.`},{status:r.status});if(direction==="inbound"){const raw=Array.isArray(j.from)?String(j.from[0]||""):String(j.from||"");const mm=raw.match(/<([^>]+)>/);const email=(mm?mm[1]:raw).trim().toLowerCase();const h=j.headers||{};const received=String(h["x-sender-ip"]||h["x-originating-ip"]||j.sender_ip||j.client_ip||"").replace(/[\[\]]/g,"").trim();await ctx.db.rpc("mail_record_sender_meta",{p_address:address,p_provider_id:String(id),p_email:email,p_ip:received||null});}return Response.json({...j,direction});
}
